### PR TITLE
Try to find the password before asking user

### PR DESCRIPTION
**Pull request by DamienCassou**
When git asks the user for a password, this patch first asks the auth-source library. If no password is found, prompt the user.

### CODE REVIEW

**Comment by tarsius** [comment]
Please fix indentation, don't change line wrapping of existing code, and make sure the compiler has nothing to complain about. Also I am wondering why there appears a literal regexp in here and whether it's really necessary/preferable to split this across three functions.

**Comment by DamienCassou** [comment]
Here is a new version. First, I want to say I'm sorry about the bad quality of the previous commit. I was in a hurry and decided to use github's edit interface instead of properly cloning your repository locally. That was clearly a bad decision. Regarding your comments:

- the compiler has nothing to say about my code
- regarding the 2nd regexp match: `auth-source` depends on the notion of `:host`: a host must be given as input to get the corresponding password. But `magit-process-password-prompt-regexps` matches against more than host password requests: this variable matches for yubikey queries, passphrases... If you have a better idea, I'd be happy to implement it. Something I could do would be to split `magit-process-password-prompt-regexps` into several regular expressions.
- regarding the split across 3 functions: I like my decomposition because each function has a precise role. Each function can then be understood separately, patched separately, advised separately. But you are the maintainer so please tell me what you prefer and I will implement it.

**Comment by npostavs** [comment]
> But magit-process-password-prompt-regexps matches against more than host password requests: this variable matches for yubikey queries, passphrases... If you have a better idea, I'd be happy to implement it.

We could require that the `magit-process-password-prompt-regexps` put host name (if any) in match group 99 (some arbitrarily large number to avoid a user-added regexp hitting it by accident).

```elisp
(let ((str "Enter password for 'foo.com':"))
  (when (string-match "^\\(Enter \\)?[Pp]assword\\( for '\\(?99:.*\\)'\\)?: ?$" str)
    (match-string 99 str))) ; => "foo.com"
```

**Comment by tarsius** [comment]
I haven't looked very closely at the code the first time because of the formatting issues and just mentioned some things that popped into my head. After having looked at the new revision I have no issues with splitting the thing across multiple functions, but if you had not done that I would have been fine with it too. So no need to change that.

I'll have to look into what exactly `auth-source` does though, I wasn't aware of its existence.

**Comment by npostavs** [comment]
Another possibility is to read netrc from git:
http://stackoverflow.com/a/6031266/319698
https://github.com/git/git/blob/master/contrib/credential/netrc/git-credential-netrc

**Comment by DamienCassou** [comment]
@npostavs ok for me. Should `99` be stored in a constant to avoid magic numbers? @tarsius what's your opinion? I guess this would avoid duplicating part of the regexp.

@tarsius [`auth-source`](https://www.gnu.org/software/emacs/manual/html_mono/auth.html) is an Emacs library to find passwords. This is how Emacs reads the `.netrc` and `.authinfo` files. `auth-source` can also read the GNOME Keyring, the KDE Wallet, and a [password store](https://github.com/DamienCassou/auth-password-store).

@npostavs please don't limit magit to `.netrc` because `auth-source` already abstracts over it.

**Comment by npostavs** [comment]
> please don't limit magit to .netrc because auth-source already abstracts over it.

`contrib/credential/netrc/git-credential-netrc` is not limited to `.netrc`:
```
  -f|--file AUTHFILE : specify netrc-style files.  Files with the .gpg extension
                       will be decrypted by GPG before parsing.  Multiple -f
                       arguments are OK.  They are processed in order, and the
                       first matching entry found is returned via the credential
                       helper protocol (see below).
                       When no -f option is given, .authinfo.gpg, .netrc.gpg,
                       .authinfo, and .netrc files in your home directory are used
                       in this order.
```

**Comment by DamienCassou** [comment]
@npostavs sorry, but this is not enough. `auth-info` handles:

- the [Secret Storage API](http://www.freedesktop.org/wiki/Specifications/secret-storage-spec/) which is implemented by Gnome Keyring and KDE Wallet
- the macos keychain
- [password-store](http://www.passwordstore.org/) (through a [plugin](https://github.com/DamienCassou/auth-password-store))

**Comment by npostavs** [comment]
Ah, well under https://github.com/git/git/tree/master/contrib/credential there is also `gnome-keyring` and `osxkeychain`. For KDE Wallet, https://blog.sleeplessbeastie.eu/2012/08/12/git-how-to-avoid-typing-your-password-repeatedly/ suggests setting `GIT_ASKPASS`. I can't find anything for password-store though.

**Comment by tarsius** [comment]
> Should 99 be stored in a constant to avoid magic numbers?

It has to be hard-coded in one place anyway, the doc-string, so you might as well hard-code it in the other two (?) places also.

**Comment by DamienCassou** [comment]
@npostavs @tarsius after looking at it more seriously, I think following @npostavs idea to use match groups will not work because `magit-process-match-prompt` uses `string-match` several times which erase previous `match-string` results:

```emacs
(defun magit-process-match-prompt (prompts string)
  (when (--any? (string-match it string) prompts)
    (let ((prompt (match-string 0 string)))
      (cond ((string-match ": $" prompt) prompt)
            ((string-match ":$"  prompt) (concat prompt " "))
            (t                           (concat prompt ": "))))))
```

**Comment by DamienCassou** [comment]
I've just added a unit-test in case you want one.

**Comment by npostavs** [comment]
> magit-process-match-prompt uses string-match several times which erase previous match-string results:

we can change the latter 2 `string-match` to `string-match-p` (or even just `string-suffix-p`), which should solve the problem.

**Comment by npostavs** [comment]
I think `magit-process-match-prompt` should get a docstring/comment noting that it preserves the match-data from a successful match.

Maybe you should use `--when-let` to avoid saying `(match-string 99 string)` twice.

Otherwise looks good to me.

**Comment by tarsius** [comment]
I had reservations about this, but considering #2309 that is fading.

I would still prefer if everyone just used public keys and got of my lawn, but that just won't happen. We maintainers have to often help users who cannot figure out how to configure credentials. Our usual approach was "configure Git then Magit can do it to", and if the follow up was "it works in Git but still not in Magit", then "you are on Windows - make 'git bash', ssh, and Magit agree on where $HOME is". @npostavs even wrote a [package](https://github.com/magit/ssh-agency) that prevents users from having to configure ssh themselves.

We also have a wiki page [Pushing with Magit from Windows](https://github.com/magit/magit/wiki/Pushing-with-Magit-from-Windows), but that isn't quite accurate anymore.

So I now think we should merge this, but it is even more important that we once more go over our instructions on the issue and document what doesn't work and why.

**Comment by npostavs** [comment]
> We also have a wiki page Pushing with Magit from Windows, but that isn't quite accurate anymore.

I just updated it, the situation with Git 2.x is actually quite a bit better (actual error messages instead of hanging, and SSH_ASKPASS works)

**Comment by DamienCassou** [comment]
@npostavs done. Anything else I can do before you merge it? I can rebase the commits and get either 1 commit or several semantic ones:

1) additions of tests to `match-prompt`
2) fix of `match-prompt` to preserve match groups + tests
3) addition of auth-source authentification + tests

Tell me what you want

**Comment by DamienCassou** [comment]
Here it is.

**Comment by tarsius** [comment]
I think I'll merge that tomorrow or so. @npostavs any objections?

**Comment by npostavs** [comment]
> any objections?

Nope, all good from my end.

**Comment by tarsius** [comment]
Do you intend to make changes? I just fetched this and was rather surprised that it had already been rebased onto changes I pushed less than an hour ago.

**Comment by tarsius** [comment]
Oh, and one commit is fine, but if you prefer three, then go with that.

**Comment by DamienCassou** [comment]
@tarsius I just wanted to help you integrate it :-). Here is one commit. I don't plan to do anything anymore on it (except if you ask me)

**Comment by tarsius** [comment]
I made some minor changes. But then I also remembered just in time, that I wanted to make this optional. I have implemented that myself, sorry. But I would still appreciate your help with this, because I have not actually tested it (I still have to get around to learn to use `auth-source`). Thanks.

Any objections to not enabling this by default?

See https://github.com/magit/magit/compare/dc/auth-source?expand=1.

**Comment by tarsius** [comment]
Ups wait a moment...

**Comment by DamienCassou** [comment]
@tarsius I gave you write access to my `magit` fork if you need

**Comment by tarsius** [comment]
Okay, so I probably should have at least run the tests once.... Done that now. Please have a look.

**Comment by DamienCassou** [comment]
It seems to work fine. Thanks

**Pull request merged**
