### PR TITLE
Stage and commit **all unstaged files**

### PR DESCRIPTION
**Pull request by ericprud**
For the last couple years, I assumed that "stage everything" included untracked files. I now assume it's more like `commit --all`.

### CODE REVIEW

**Comment by tarsius** [comment]
I think "all unstaged **files**" is still ambigious - untracked files are also "not staged". "All unstaged **changes**" might be better. What do others think?

**Comment by ericprud** [comment]
That makes sense to me. I've optimistically updated the PR to be "all unstaged changes".

**Comment by kyleam** [comment]
s/everything/all staged changes/ sounds fine to me

**Comment by kyleam** [comment]
> @kyleam, I think you meant "all unstaged changes".

Indeed.  Thanks.

**Comment by tarsius** [comment]
Thanks!

I rebased, squashed, bumped version strings, and improved commit message.

**Pull request closed without merging**
