### PR TITLE
magit-describe-section for users

### PR DESCRIPTION
**Pull request by npostavs**
v2 of #3505 (see also #3308 for initial suggestion).

### CODE REVIEW

**Comment by npostavs** [comment]
I think this should be ready now, modulo regenerating the manual.

While testing this out, I did notice some slightly odd section navigation in the revision buffer:

> `Parent:     6d72f0ee magit-no-confirm: Fix description of Custom choice item`
> Merged:     `maint` `master`
> Containing: `master` `np/section-desc-v2`
> `Follows:    2.13.0 (107)`

The entries after "Merged" and "Containing" each act as their individual sections, whereas the "Parent" and "Follows" are just single sections over the whole line. Is that on purpose? It seems like it would be more consistent to have the word before the colon not be part of the section every time, or else it should always be part of the section.

**Comment by tarsius** [comment]
> While testing this out, I did notice some slightly odd section navigation in the revision buffer:

I think that's okay. There's only one parent and git only spits out one tag that follows. It's the other lines that are unusual, so I don't think we should make the regular lines behave in an unusual way just because there are unusual lines close by. Of course doing that would also make sense, i.e. both approaches make sense and I favor sticking with what we have.

**Comment by tarsius** [comment]
I added a fixup commit that wraps lines a bit differently just in case the name of the section inserted is long (I just tried it with `magit-insert-unpushed-to-upstream-or-recent`).

(I already rebased and updated the manual before I noticed that I wanted to make that change.)

**Comment by npostavs** [comment]
> both approaches make sense and I favor sticking with what we have.

Fine with me.

> I added a fixup commit that wraps lines a bit differently just in case the name of the section inserted is long (I just tried it with magit-insert-unpushed-to-upstream-or-recent).

Hmm, should the `called by ...` get the same treatment to stay consistent? (this shows up when describing any of the header sections)

**Comment by tarsius** [comment]
> Hmm, should the called by ... from ... get the same treatment to stay consistent?

I think so.

> `#<magit-section #("master" 0 6 (face magit-branch-local)) [branch branch status] 73-148>`

If the section value is a string, then we should remove all properties.

**Comment by npostavs** [comment]
Okay, done those. I will merge to master tomorrow, since it's getting a bit late here, and I've found it's better to do that only when I'm fully awake.

**Pull request merged**
