### PR TITLE
Don't downcase keys when getting values from cache

### PR DESCRIPTION
**Pull request by ptrv**
See #2684

### CODE REVIEW

**Comment by npostavs** [comment]
This doesn't work because *most* keys are downcased by `git config --list`.

**Comment by ptrv** [comment]
The outer keys are anyways always lower case, aren't they?

**Comment by npostavs** [comment]
No, typically the last key is camelCased.

**Comment by ptrv** [comment]
Ok, what should we do about this PR. Do you have some suggestions for me to apply here or should I close the PR?

**Comment by npostavs** [comment]
Well if you can change it to downcase the first and last keys as mentioned in https://github.com/magit/magit/issues/2684#issuecomment-224567876, then it could work.

**Comment by ptrv** [comment]
What I don't get is why then `magit-git-str` uses `'identity` for mapconcat when it gets the config value?
Is only `git config --list` downcasing? Can you point me to the docs?

**Comment by npostavs** [comment]
`man git-config(1)` says

> --get-regexp
>
>    Like --get-all, but interprets the name as a regular expression and writes out the key names. Regular expression matching is currently case-sensitive and done against a canonicalized version of the key in which section and variable names are lowercased, but subsection names are not.

It's not specified for `--list`, but it seems to work the same.

**Comment by ptrv** [comment]
Thanks for the pointer to the docs. Yes, `git config --list` works the same. I could reproduce it myself.

I wonder if we add code to downcase only the key and the section part, would it make the performance benefit of using the hashtable void?

Can't we just use the `identity` function in mapconcat and require the user of the function to pass downcased key and section?

Or just use `magit-git-str` again?

What do you think?

**Comment by npostavs** [comment]
> I wonder if we add code to downcase only the key and the section part, would it make the performance benefit of using the hashtable void?

As I mentioned in #2670, the performance benefits are only seen on Windows, but it's more than 100ms there. I doubt a couple of string transformations will be noticable either way.

> Can't we just use the `identity` function in mapconcat and require the user of the function to pass downcased key and section?

Well it would simplify things a bit, but on the other hand `magit-get` calls would be slightly harder to read. @tarsius what do you think?

> Or just use `magit-git-str` again?

Nah, I don't want to give up even a few hundred ms towards making magit usable on Windows.

**Comment by npostavs** [comment]
Closing in favour of #2688.

**Comment by ptrv** [comment]
@npostavs Thanks for your answer. I agree that the 100 ms benefit on windows is quite important to keep.

**Pull request closed without merging**
