### PR TITLE
Use absolute path for magit-emacs-Q-command load file

### PR DESCRIPTION
**Pull request by fice-t**
This matches the absolute paths for library directories.

### CODE REVIEW

**Comment by npostavs** [comment]
But setting up the library directories should make specifying the path loading `magit` redundant, no?

**Comment by fice-t** [comment]
It seems that when using `-l", it tries to load from the current directory first. The reason I made this patch is when I execute the command from `~`, then I get:

```elisp
Debugger entered--Lisp error: (file-error "Cannot open load file" "Is a directory" "/home/alex/magit")
  load("/home/alex/magit" nil t)
  command-line-1(("--eval" "(setq debug-on-error t)" "-L" "/home/alex/.emacs.d/elpa/magit-20161208.1727/" "-L" "/home/alex/.emacs.d/elpa/magit-popup-20161207.613/" "-L" "/home/alex/.emacs.d/elpa/with-editor-20161201.925/" "-L" "/home/alex/.emacs.d/elpa/git-commit-20161206.1703/" "-L" "/home/alex/.emacs.d/elpa/dash-20161105.557/" "-l" "magit"))
  command-line()
  normal-top-level()
```

**Comment by npostavs** [comment]
Ah, [Emacs bug#16406](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=16406). I fixed that recently, but that's only for Emacs 26, so we should indeed make `magit-emacs-Q-command` work for earlier versions, even if the user happens to execute just above the magit directory (it's supposed to be foolproof after all).

**Comment by fice-t** [comment]
Good to know, thanks for fixing it upstream.

**Pull request merged**
