### PR TITLE
cache git config more aggressively (v2)

### PR DESCRIPTION
**Pull request by npostavs**
This is a new version of #2670, with fixes for all the issues that came up since then (& tests for those issues).

### CODE REVIEW

**Comment by tarsius** [comment]
I have applied the following change to your commit, rebased onto master, and merged into pu.

```diff
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index 304f3a1..7372361 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -1428,24 +1428,25 @@ (defun magit-read-remote-or-url (prompt &optional default)
 ;;; Variables
 
 (defun magit-config-get-from-cached-list (key)
-  (gethash ;; `git config --list' downcases first and last components
-           ;; of the key.
-           (replace-regexp-in-string
-            "[^.]+\\'" #'downcase
-            (replace-regexp-in-string "\\`[^.]+" #'downcase key t t)
-            t t)
-           (magit--with-refresh-cache (list 'config (magit-toplevel))
-             (let ((configs (make-hash-table :test 'equal)))
-               (dolist (conf (magit-git-items "config" "--list" "-z"))
-                 (let* ((nl-pos (cl-position ?\n conf))
-                        (key (substring conf 0 nl-pos))
-                        (val (if nl-pos (substring conf (1+ nl-pos)) "")))
-                   (puthash key (nconc (gethash key configs) (list val)) configs)))
-               configs))))
+  (gethash
+   ;; `git config --list' downcases first and last components of the key.
+   (--> key
+        (replace-regexp-in-string "\\`[^.]+" #'downcase it t t)
+        (replace-regexp-in-string "[^.]+\\'" #'downcase it t t))
+   (magit--with-refresh-cache (list 'config (magit-toplevel))
+     (let ((configs (make-hash-table :test 'equal)))
+       (dolist (conf (magit-git-items "config" "--list" "-z"))
+         (let* ((nl-pos (cl-position ?\n conf))
+                (key (substring conf 0 nl-pos))
+                (val (if nl-pos (substring conf (1+ nl-pos)) "")))
+           (puthash key (nconc (gethash key configs) (list val)) configs)))
+       configs))))
 
 (defun magit-get (&rest keys)
   "Return the value of Git config entry specified by KEYS."
-  (car (last (apply 'magit-get-all keys))))
+  ;; FIXME https://github.com/magit/magit/commit/11e14785fba9e2476e195af272fff3a4f5dc149b
+  ;; (car (last (apply 'magit-get-all keys)))
+  (magit-git-str "config" (mapconcat 'identity keys ".")))
 
 (defun magit-get-all (&rest keys)
   "Return all values of the Git config entry specified by KEYS."
@@ -1453,7 +1454,7 @@ (defun magit-get-all (&rest keys)
         (key (mapconcat 'identity keys ".")))
     (if magit--refresh-cache
         (magit-config-get-from-cached-list key)
-      (magit-git-items "config" "-z" "--get-all" (mapconcat 'identity keys ".")))))
+      (magit-git-items "config" "-z" "--get-all" key))))
 
 (defun magit-get-boolean (&rest keys)
   "Return the boolean value of Git config entry specified by KEYS."
diff --git a/t/magit-tests.el b/t/magit-tests.el
index a614435..13d2eff 100644
--- a/t/magit-tests.el
+++ b/t/magit-tests.el
@@ -146,6 +146,7 @@ (defun magit-test-magit-get ()
   (should (equal (magit-get "a.b2") "line1\nline2")))
 
 (ert-deftest magit-get ()
+  :expected-result :failed ; "Values with newline" fails for now
   (magit-with-test-directory
    (magit-git "init" "remote")
    (let ((default-directory (expand-file-name "remote/")))
```

**Comment by npostavs** [comment]
> ```diff
> -  (car (last (apply 'magit-get-all keys))))
> +  ;; FIXME https://github.com/magit/magit/commit/11e14785fba9e2476e195af272fff3a4f5dc149b
> +  ;; (car (last (apply 'magit-get-all keys)))
> ```

Do you not think `(car (last...))` is correct?

**Comment by tarsius** [comment]
For the benefit of others:

```
$ git config --global name.user global
$ git config name.user local
$ git config --get-all name.user
global
local
```

I did not notice that you changed `(car ...)` to `(car (last ...))`. The latter indeed does the right thing here, and I am going to revert my change and remerge into `pu`.

**Comment by tarsius** [comment]
I've merged that now. I think I did not merge it earlier because I wanted to get a subminor release out first, but that ship has sailed a long time ago.

**Pull request merged**
