### PR TITLE
allow magit-file-mode to work in dired buffers

### PR DESCRIPTION
**Pull request by jpkotta**

### CODE REVIEW

**Comment by tarsius** [comment]
At least the blame commands won't work in a dired buffer. The others commands in the popup have to be checked too.

**Comment by jpkotta** [comment]
I mostly want to use `magit-status` and `magit-dispatch-popup`.  Diff and log commands in `magit-file-popup` applied to a directory would be handy.  The other commands in `magit-file-popup` might not be all that useful when applied to a directory.  I can try to generalize the diff and log commands in the file popup for directories, if you think that would be worthwhile.

**Comment by jpkotta** [comment]
I mostly want to use `magit-status` and `magit-dispatch-popup`.  I think it would be handy to be able to diff and log a subdirectory from a dired buffer.  I can try to generalize the log and diff commands in the file menu if you think that would be worthwhile.

**Comment by tarsius** [comment]
> I can try to generalize the diff and log commands in the file popup for directories, if you think that would be worthwhile.

Where it makes I intend to do that too, but only once I have implemented `git-handler.el` (#2958).

> I mostly want to use `magit-status` and `magit-dispatch-popup`.

Why not just bind those keys in `dired-mode-map` (or globally as recommended in [Getting Started](https://magit.vc/manual/magit/Getting-Started.html)?

**Pull request closed without merging**
