### PR TITLE
Stash ediffing

### PR DESCRIPTION
**Pull request by kyleam**
Re: #2575

### CODE REVIEW

**Comment by tarsius** [comment]
Looks good to me. I only did some limited testing, but that it passed at least.

**Comment by kyleam** [comment]
Thanks for you comments.  I'll incorporate them and merge tomorrow unless @michael-heerdegen has any additional feedback.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> Thanks for you comments. I'll incorporate them and merge tomorrow
> unless @michael-heerdegen has any additional feedback.

Hi, sorry, I could not yet have a closer look at the stuff due to the
flu in the family.  I'll try to have a look today.


Thanks so far,

Michael.

**Comment by kyleam** [comment]
> Hi, sorry, I could not yet have a closer look at the stuff due to the
> flu in the family. I'll try to have a look today.

OK, no rush.  I'll wait for you to try it out before applying.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> OK, no rush. I'll wait for you to try it out before applying.

I had a look now.  Looks very good so far, I like it, thanks!


The only little "discrepancy" I found:

The doc of magit-ediff-show-stash-with-index says:

| * stash@{N}^1 represents the HEAD commit at the time the stash
|   was created.

But when I create a stash with z W (aka "snapshot worktree"),
stash@{N}^1 is actually a "pre stash index" - dunno if it comes from git
itself or from Magit.  So you get an (two way) ediff stashed worktree
vs. index, which was a bit surprising to me.  But maybe this is
expected?


Btw, when you will have merged this PR, will this change appear
in Melpa?


Thanks again - regards,

Michael.

**Comment by kyleam** [comment]
> I had a look now. Looks very good so far, I like it, thanks! 

Thanks for having a look.

> The only little "discrepancy" I found:
>
> The doc of magit-ediff-show-stash-with-index says:
>
> | * stash@{N}^1 represents the HEAD commit at the time the stash
> |   was created.
>
> But when I create a stash with z W (aka "snapshot worktree"),
> stash@{N}^1 is actually a "pre stash index" - dunno if it comes from git
> itself or from Magit.

It's in Magit's implementation of the snapshot functionality.

> So you get an (two way) ediff stashed worktree
> vs. index, which was a bit surprising to me.  But maybe this is
> expected?

It is expected/intentional in that `stash@{N}^1..stash@{N}` gives you
the changes that were in the working tree.  This is the same as
diffing `stash@{N}^^..stash@{N}` and filtering out changes that were
staged, unless a staged changed involved the same hunk as an unstaged
change.

However, as you point out, it does make the description wrong (though
right in spirit) in the case of a working tree snapshot.  I'm not sure
what the best way to clarify this is.

> Btw, when you will have merged this PR, will this change appear
> in Melpa?

Yes.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> However, as you point out, it does make the description wrong (though
> right in spirit) in the case of a working tree snapshot. I'm not sure
> what the best way to clarify this is.

Are there more such "corner cases"?


>  Btw, when you will have merged this PR, will this change appear
>  in Melpa?
>
> Yes.

Great! :-)

**Comment by kyleam** [comment]
> It's in Magit's implementation of the snapshot functionality.

Sorry, I said the wrong thing there.  It's Magit's implementation for
letting you make a stash of just unstaged changes (that is,
magit-stash-worktree and magit-snapshot-worktree).

**Comment by kyleam** [comment]
> Are there more such "corner cases"?

I think the two worktree functions are it.

**Comment by kyleam** [comment]
I suppose it's worth noting that I find `magit-stash-worktree` and
`magit-snapshot-worktree` confusingly named because they capture just
the unstaged changes, not all changes in working tree.

**Comment by kyleam** [comment]
The pushed update incoporates @tarsius's suggestions.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> I suppose it's worth noting that I find magit-stash-worktree and
> magit-snapshot-worktree confusingly named because they capture just
> the unstaged changes, not all changes in working tree.

Indeed, such things are very confusing especially to beginners.  And the
docstring doesn't explain this as well.

Would "magit-snapshot-unstaged" be a better name?

**Comment by tarsius** [comment]
I agree that we should consider renaming these functions and/or clarifying the documentation, but that shouldn't block the merge of this.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I agree that we should consider renaming these functions and/or
> clarifying the documentation, but that shouldn't block the merge of
> this.

Great, than - let's merge!

Shall I create a new issue for the confusing command names?

**Comment by kyleam** [comment]
Merged.

> Shall I create a new issue for the confusing command names?

There are at least a couple other cases where worktree is used this
way, so I can take care of looking through those and opening an issue
or PR for discussion.

**Pull request merged**
