### PR TITLE
Copyedit documentation

### PR DESCRIPTION
**Pull request by seh**
Function `magit-maybe-show-setup-instructions` presents a warning and
some configuration advice when the `magit-last-seen-setup-instructions`
variable's value suggests that the user hasn't seen it yet. Adjust the
language for an American English-appropriate tone.

### CODE REVIEW

**Comment by seh** [comment]
I realized after the fact that I started this change atop the `magit/next` branch, as opposed to `magit/master` as suggested in aa72a592b27edcda326255c4310cc4b60f5bbd4e. Please let me know if you want to try again with a different request.

**Comment by npostavs** [comment]
I think you just need to rebase to `master` then `push -f`.

**Comment by tarsius** [comment]
I fixed up the commit slightly to preserve the original (and quite intentional) filling.

In the process I learned that `--no-commit` does not what I would want it to do. With regards to this `git cherry-pick` is not consistent with other commands which allow "applying" a commit but also edit it, *without* having to manually preserve the message. I will look into a workaround.

I also realized that `magit-commit-extend` probably should not preserve the `GIT_COMMIT_DATE` when the `AUTHOR` is not "me".

**Comment by seh** [comment]
I too find _git cherry-pick_ confusing in that regard. I guess it offers the `CHERRY_PICK_HEAD` ref that you can use to grab the commit message via

> _git commit (-C |--reuse_message=)CHERRY_PICK_HEAD_

, or if you want to edit the message, you can use the similar

> _git commit (-c |--reedit_message=)CHERRY_PICK_HEAD_

command.

**Pull request closed without merging**
