### PR TITLE
git-commit: Ignore leading comment when inserting headers

### PR DESCRIPTION
**Pull request by magnars**
It is suggested several places on the internet to use a git commit template, for instance
[here](https://gist.github.com/lisawolderiksen/a7b99d94c92c6671181611be1641c733). These often include a header comment:

    # Title: Summary, imperative, start upper case, don't end with a period
    # No more than 50 chars. #### 50 chars is here:  #

This change ensures that headers are inserted after this leading comment, instead of above it.

### CODE REVIEW

**Comment by magnars** [comment]
I was a bit quick on the trigger. This code will only ignore a single leading comment line. I'll brew up something a bit more robust.

**Comment by magnars** [comment]
This updated version will skip past any leading comments, make a note of where they are, and then make sure to insert the header before any comments except the leading ones.

**Comment by tarsius** [comment]
Thanks!

**Comment by magnars** [comment]
Thank you! 🙏😊

**Pull request merged**
