### PR TITLE
Basic libgit support

### PR DESCRIPTION
**Pull request by tarsius**
Description coming soon. (Need to coordinate changes to three repositories.)

### CODE REVIEW

**Comment by tarsius** [comment]
I am deleting the earlier iterations now but just in case I am recording the old &context magic here:

``` emacs-lisp
;; We want to write (&context (gitimpl IMPL)), which is only possible
;; if a variable `gitimpl' exists.  We don't use it for anything but
;; satisfying that requirement.  `cl-generic' assumes the use of a
;; variable, but we use a function to determine the context.
(with-no-warnings (defvar gitimpl nil))
(defun cl--generic-gitimpl-tagcode (varsym &rest _)
  `(progn ,varsym ; silence byte-compiler
          (let ((val (magit--git-implementation)))
            (and (memq val magit--git-implementations) val))))

(defun cl--generic-gitimpl-generalizers (tagval &rest _)
  `((gitimpl ,tagval)))

(cl-generic-define-generalizer cl--generic-gitimpl-generalizer
  80
  #'cl--generic-gitimpl-tagcode
  #'cl--generic-gitimpl-generalizers)

(cl-defmethod cl-generic-generalizers ((_specializer (head gitimpl)))
  (list cl--generic-gitimpl-generalizer))

(cl-generic-define-context-rewriter gitimpl (impl &rest impls)
  `(gitimpl ,(if (consp impl)
                 (progn (cl-assert (null impls)) impl)
               `(gitimpl ,impl . ,impls))))
```

**Comment by ethomson** [comment]
Excited to see this!  I'm sorry that I didn't see this earlier, because I would want to point out that libgit2 is actually _libgit2_, which is the proper name of the library.  (It's not "libgit", version "2"; which is a common misunderstanding for obvious reasons.)

libgit itself is the shared library that is part of git, the command-line application.  So there's some ambiguity calling it simply "libgit".

(Actually, libgit2 _was_ originally intended to replace that libgit that's in git, while providing a linkable library for everybody else, too.  But that's not really what happened, I guess, and here we are.)

Anyway.  I just wanted to mention this.  I don't expect you to necessarily change this if it's a) obviously too late, or b) you don't care.  But if this is something that you care about then I wanted to mention it before it was _way_ too late.  😉 

Excited again to see this.  Please let me know if the libgit2 developers can help with anything!

**Comment by slyrus** [comment]
I second the notion that calling the libegit2 directory libgit is user-unfriendly and confusing. It would be great if this could just work with that directory being named libegit2.

**Comment by tarsius** [comment]
Thanks for the feedback.

If there is a last chance to change the name, then it is now.

I don't think we talked much about the name in the past, and the extend of the "conversation" is:

1. (1) of https://github.com/magit/magit/issues/2959#issuecomment-383221426 and
2. the reply to that in https://github.com/magit/magit/issues/2959#issuecomment-383276092.

One difficulty is that Emacs Lisp doesn't do namespaces. Different packages avoid trampling on each others foot by using dedicated symbol prefixes. These prefixes should match the name of the package. The name of the package must match the name of the primary lisp library of the package.

So if we change the name of the package, then we don't only have to rename the library to `libgit2.el`, we *should* also change the symbol prefixes to `libgit2-` and rename all the symbols.

I would rather not do that. It is a unwieldy; its a bit long and makes touch typing harder.

I guess the reason we use the `libgit-` prefix instead of `libgit2-` is the same as why libgit2 itself uses `git-` instead of `libgit2-`. We just couldn't go as far because of the lack of namespacing. `libgit2` isn't "git", so the symbol prefix that it uses is "not correct". But you concluded that this doesn't matter because once you actually use these function you already know how `libgit2` relates to `git` and how they are not the same thing.

In our case the choice of symbol prefix leaks into the name of the library and the package; at least by convention. While the names of the library and the package *must* match, the prefix only *should* match.

There aren't that many C modules yet, so the conventions haven't been challenged much yet when it comes to this special-case. We do have the option to name the package and library `libgit2` (or `libegit2`, `egit`...) and keep the `libgit-` symbol prefix. Lets summon someone who does a lot of convention enforcement.

@purcell we call to you to bless us with your  guidance. :wink: 

Also @TheBB is who will ultimately decide, so :wave:, please join in too.

**Comment by basil-conto** [comment]
FWIW, there is slightly related precedent with, for example, Emacs linking to `libxml2` and exposing it via `libxml-*` functions.

**Comment by tarsius** [comment]
@basil-conto Thanks for the information. I know favor doing the same here.

**Pull request merged**
