### PR TITLE
magit-format-patch: support <since> commit

### PR DESCRIPTION
**Pull request by kyleam**
Thoughts?

### CODE REVIEW

**Comment by tarsius** [comment]
Lets delay this until we start working on `2.3.0` (branching and pushing). https://github.com/magit/magit/issues/1800 is the umbrella issue for this sort of thing.

I had a short look and think that this change, by itself, does not provide much. We don't have to support <since>, just because git does.

>Do not convert a single commit argument read by magit-format-patch to '<commit>^..<commit>' because this prevents the user from giving a single commit argument that has the same meaning as it does for 'git format-patch', where it is interpreted as '<commit>..HEAD'.

On the other hand what you propose makes it harder to create a patch for a single commit. We can get `<commit>..HEAD` quite easily: set mark on the first commit in "Unpushed commits", move down, press `W p`.

**Comment by kyleam** [comment]
Thanks for your comments.

> Lets delay this until we start working on `2.3.0` (branching and
> pushing).

Sure.

> We don't have to support <since>, just because git does.

Yes, but I'm in favor of interpreting user-inputted ranges in the same
way as the underlying git command would, rather than modifying them
before passing them down.

> On the other hand what you propose makes it harder to create a patch
> for a single commit.

With point at the commit, commit^..commit would be the default prompt,
so it is only more difficult if the user wants to manually input a
commit to get commit^..commit (which I suspect for many users is not the
expectation, given the behavior of git format-patch).

**Comment by tarsius** [comment]
Well, I am not completely against this. (Really I just haven't had a close look yet.) So you probably want to keep the branch around. Unless you have something better cooking of course.

**Comment by kyleam** [comment]
Yep, I'll keep it around (plus it's in pull/origin), but, since this PR is mentioned in #1800 and can be revisited with that, I figured there is no advantage to leaving this open.

**Pull request closed without merging**
