### PR TITLE
cache git config more aggressively

### PR DESCRIPTION
**Pull request by npostavs**
It shaves a couple 100 ms or so from refreshing the status

With `master`:
```
Refreshing magit...done (1.107s, cached 27/53)
Refreshing magit...done (1.107s, cached 27/53)
Refreshing magit...done (1.108s, cached 27/53)
```

With the patch:
```
Refreshing magit...done (0.921s, cached 33/53)
Refreshing magit...done (0.936s, cached 33/53)
Refreshing magit...done (0.951s, cached 33/53)
```

### CODE REVIEW

**Comment by tarsius** [comment]
Yes, let's do that.

I am not a fan of the order of `magit-set`s arguments. To avoid mistakes I would recommend using `(magit-set value "single.variable.string")` when all parts of the variable name are constant. Or maybe we should deprecate `magit-{get,set}` and add `magit-config-{get,set,unset}` like:

```lisp
(defun magit-config-set (&rest args)
  "Set the value of the Git VARIABLE to VALUE.
\n(fn VARIABLE [VARIABLE-PART...] VALUE)"
  (magit-git-string "config"
                    (mapconcat #'identity (butlast args) ".")
                    (car (last args))))

(defun magit-config-unset (variable &rest variable-part)
  (magit-git-string "config" "--unset" (cons variable variable-part)))
```

**Comment by npostavs** [comment]
While I was writing this code, I had the idea that we could somehow use the `gv` machinery so that `magit-set` could be done with `(setf (magit-get <var>) <value>)`.

**Comment by tarsius** [comment]
I like your idea better than what I previously suggested.

**Comment by npostavs** [comment]
Dropping the changes to `magit-set`, it's not really related to this; it just happened to come up when I grepped for `git config` calls. I'll do the `setf` thing later.

---

Oh, by the way, the original timings were on Windows, on GNU/Linux there's not really a difference:

`master`
```
Refreshing magit...done (0.123s, cached 24/52)
Refreshing magit...done (0.124s, cached 24/52)
Refreshing magit...done (0.160s, cached 24/52)
```

with patch
```
Refreshing magit...done (0.161s, cached 29/52)
Refreshing magit...done (0.103s, cached 29/52)
Refreshing magit...done (0.108s, cached 29/52)
```

**Pull request closed without merging**
