### PR TITLE
magit-find-file: Fix docstring typo

### PR DESCRIPTION
**Pull request by kyleam**

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks.

This is the first pr that got integrated with the help of https://github.com/tarsius/magit-rockstar/commit/3eb7353f110dcda48dcbbeb88590f4912272f0e8 :-)

**Comment by kyleam** [comment]
My 1 character commit's 15 minutes of fame

**Comment by tarsius** [comment]
lol

**Comment by tarsius** [comment]
Lets make its dream come true: https://twitter.com/magit_emacs/status/619145823792836608

**Pull request closed without merging**
