### PR TITLE
Keep GitHub Actions up-to-date with Dependabot

### PR DESCRIPTION
**Pull request by skangas**
This adds a daily check that GitHub Actions in workflows are up-to-date using Dependabot.

More information here:
https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file
https://docs.github.com/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks, but until Github gets their act together and addresses https://github.com/dependabot/dependabot-core/issues/2804, I am not comfortable using Dependabot. It's not okay to spam everyone who forks this repository (much less everybody who forks any repository that uses Dependabot).

> 1694 hidden items
> Load more...

On a recent duplicate (https://github.com/dependabot/dependabot-core/issues/5914), it was said that "a permanent fix should land in the next couple of weeks". Let's wait until that time comes.

**Comment by skangas** [comment]
Thanks for making me aware of this issue. Your conclusion makes sense to me.

**Comment by skangas** [comment]
> On a recent duplicate ([dependabot/dependabot-core#5914](https://github.com/dependabot/dependabot-core/issues/5914)), it was said that "a permanent fix should land in the next couple of weeks". Let's wait until that time comes.

There has been an update here: https://github.com/dependabot/dependabot-core/issues/2804#issuecomment-1326137957

**Comment by tarsius** [comment]
Thanks, I've merged this now.

I have removed the comments because they seemed kinda unnecessary and because the urls are disgustingly long. I've added one of the url to the commit message instead. :grin:

**Pull request merged**
