### PR TITLE
Allow switching to toplevel directory from a subdirectory of repo.

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
Hi, 

with 1.4.2 I was able to open magit-status from helm, now it is possible only from toplevel directory.
Now I am prompted for creation of a new repo:

.../github/magit/ is a repository.  Create another in .../github/magit/lisp/? (y or n)

I added a new var to not be prompted when toplevel dir exists, otherwise if it doesn't exists
you are anyway prompted.

Perhaps you will want to change the var name which is not the best, I hope also my changes don't modify the original behavior too much.

Thanks.

### CODE REVIEW

**Comment by tarsius** [comment]
I don't know how helm calls `magit-status` but unless it does so using `call-interactively` then it should be using `magit-status-internal` instead (which is a misnomer, it should be called `magit-status-non-interactive` or something like that).

Have you tried using that function?

**Comment by thierryvolpiatto** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I don't know how helm calls magit-status but unless it does so using
> call-interactively then it should be using magit-status-internal
> instead (which is a misnomer, it should be called
> magit-status-non-interactive or something like that).
>
> Have you tried using that function?

No, will try soon, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
Yes, `magit-status-internal` is working fine.
It is not autoloaded though.
So perhaps you can close this PR.

Thanks.

**Comment by tarsius** [comment]
I've added the autoload.

**Comment by thierryvolpiatto** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I've added the autoload.

Great, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Pull request closed without merging**
