### PR TITLE
Apply new/deleted/renamed files and checkout stages

### PR DESCRIPTION
**Pull request by tarsius**
This should address #2007 and #1988. But still needs testing - especially the last commit, which also has to be split into multiple commits.

### CODE REVIEW

**Comment by kyleam** [comment]
Works well for initial tests on my end.  Thanks.

**Comment by bastianbeischer** [comment]
I'll also test!

**Comment by bastianbeischer** [comment]
#1988 is not fixed, but #2007 seems to be resolved.

**Comment by kyleam** [comment]
me:
> Works well for initial tests on my end. 

@bastianbeischer:
>#1988 is not fixed, but #2007 seems to be resolved.

Sorry, I should have specified that I only checked the #2007 issues, not the #1988 issues.

**Comment by tarsius** [comment]
I'll merge the #2007 part and open a new pr for the #1988, after I have addressed the points raised so far and setup a testing repo.

**Pull request closed without merging**
