### PR TITLE
Add new line and fix indent

### PR DESCRIPTION
**Pull request by aaa707**
I guess a new line is missing.
Thanks,

### CODE REVIEW

**Comment by aaa707** [comment]
Also, I've added a current user info into header.
I'm using some accounts, so it's convenient to show the current user.

**Comment by npostavs** [comment]
> I'm using some accounts, so it's convenient to show the current user.

I don't think it makes sense as a default though.

**Comment by tarsius** [comment]
Thanks. I have cherry-picked.

> I don't think it makes sense as a default though.

I agree and left that out.

**Comment by aaa707** [comment]
Thanks for merging.

> I don't think it makes sense as a default though.

Yes, so I don't set as a default.

**Pull request closed without merging**
