### PR TITLE
Add more fontification to git-commit.el

### LINKED ISSUE #2772: git-commit font-lock improvements
- [x] Was a non-empty 2nd line intended to be highlighted like an overly long summary line? It's currently not highlighted at all for me.
- [ ] It would be nice if the branches in the following comment lines were highlighted just like `# On branch master` is:

`# Your branch is up-to-date with 'origin/master'.`
`# Your branch and 'origin/master' have diverged,`
`# Your branch is ahead of 'origin/master' by 1 commit.`
`# Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.`
- [ ] It'd also be nice if the numbers used in the above were highlighted as well.
  The diverged case has the extra line: `# and have 1 and 1 different commits each, respectively.`
- [ ] Highlighting squash commit comments would be great as well. Some example lines that could be highlighted:

```
# This is a combination of 27 commits.
# The first commit's message is:
# This is the 2nd commit message:
# This is the 3rd commit message:
# This is the n{th,st,nd,rd} commit message:

# Author:    name <email>
# Date:      Fri Oct 31 10:13:44 2014 -0400
# interactive rebase in progress; onto 7e16917

# Last commands done (35 commands done):
#    squash ad6b85d Some commit
#    squash 75bd5c7 Other commit

# Next commands to do (30 remaining commands):
#    pick 1523650 Some commit
#    pick 458b500 Other commit

# You are currently editing a commit while rebasing branch 'master' on '7e16917'.
```

`Magit 20160902.1451, Git 2.9.3, Emacs 25.1.3, gnu/linux`

### PR DESCRIPTION
**Pull request by fice-t**
This includes font-lock support for squash commit comments.

Closes #2772.

### CODE REVIEW

**Comment by tarsius** [comment]
For some reasons I keep making comments before I have thought things through. It probably has to do with me not really wanting to deal with this right now. But it also does not help that the code is here, while the discussion is at #2772. That makes things a bit confusing, especially because there also your very similar *rebase* issue, and I keep getting things mixed up.

So lets discuss here from now on.

**Comment by tarsius** [comment]
Could let this rest for a while please?

**Comment by tarsius** [comment]
I am struggling to get some things working that I would want you to rebase your changes onto, see https://github.com/magit/magit/compare/jb/font-lock?expand=1. Can we let this rest for a while please?

**Comment by fice-t** [comment]
Sure, there's no rush. I probably won't have too much free time after today for a while.

Though what's up with the `(eval .` in your changes? I was thinking that the format of the keywords should be changed so that `nconc` could be used instead of `append`, but not like that.

**Comment by tarsius** [comment]
> Though what's up with the `(eval .` in your changes?

It's a special syntax that allows storing the result in a variable (as it is supposed to) instead of having to use a function:

```
‘(eval . FORM)’
     Here FORM is an expression to be evaluated the first time this
     value of ‘font-lock-keywords’ is used in a buffer.  Its value
     should have one of the forms described in this table.
```

**Comment by tarsius** [comment]
See https://github.com/magit/magit/pull/3307#issuecomment-351782635.

**Pull request closed without merging**
