### PR TITLE
release notes: consistency and corrections

### PR DESCRIPTION
**Pull request by dunn**
Sometimes LaTeX-style
```
`single quotes'
```
are used, other times backticks are placed on both sides.  I switched everything to the latter.

### CODE REVIEW

**Comment by tarsius** [comment]
Uhh, unfortunately the intention was to use the former :(

**Comment by dunn** [comment]
No problem, I'll just switch them all to the former.

**Comment by dunn** [comment]
Or should commands be surrounded by backticks and everything else quoted?

**Comment by tarsius** [comment]
```
`everything' except "terms"
```

:-)

**Comment by dunn** [comment]
Done, and another commit pushed with more general tweaks.

**Pull request merged**
