### PR TITLE
Fix cached config --list lookup

### LINKED ISSUE #2684: magit-get fails to retrieve branch with upcase letters
Hi,

since commit c3d55c81d24fb6694b155bad74566e81beb30914 `magit-get` retrieves the information from cache if activated.
However it fails to get remote branch if the branch name consists upper-case letters because `mapconcat` is used with `'downcase`. Why `downcase`?

The observed behavior is that in `magit-status` buffer in the header there is nor `Merge:` line anymore, even with upstream branch configured. Also pushing works and upstream branch is shown.

Repro steps:
Create branch with uppercase letters and configure as `branch.*name*.merge`.

Thanks

### PR DESCRIPTION
**Pull request by npostavs**
Fixes #2684.

```
git config --list outputs the key names with the first and last
components downcased.  Therefore we have to canonicalize the key value
before looking it up in the hash table.
```

### CODE REVIEW

**Comment by ptrv** [comment]
I can confirm that this fixes #2684

**Comment by tarsius** [comment]
I had to revert the config cache because it has an additional problem. The `default-directory` also has to be taken into account or the values from the super-repository end up being used inside submodules. This might turn out to be a bit complicated, and there are probably multiple ways of implementing this, so I have reverted for now.

**Comment by npostavs** [comment]
I've squashed the config cache commits and pushed to `np/config-cache`, I'll take a look at the submodule config thing later.

**Comment by npostavs** [comment]
> The default-directory also has to be taken into account or the values from the super-repository end up being used inside submodules.

Where does this come into play?

**Comment by tarsius** [comment]
In `magit-insert-submodules` for example.

**Comment by npostavs** [comment]
> In magit-insert-submodules for example.

That doesn't call `magit-get`, does it?

**Comment by tarsius** [comment]
Maybe not. `magit-insert-modules-unpulled-from-pushremote` does. It uses `magit-get-push-branch` which uses `magit-get-push-remote`, which uses `magit-get`.

**Pull request closed without merging**
