### PR TITLE
[doc] remove remaining references to with-editor

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks.

I changed the prefixes of the commit messages and dropped the added quotes you around the yaml variable value.

**Comment by dunn** [comment]
The quotes are necessary; otherwise `CURL` is set simply to 'curl': https://travis-ci.org/magit/magit#L109

**Comment by tarsius** [comment]
Could you please create a new commit which says so. Thanks.

**Comment by dunn** [comment]
No problem; sorry for not explaining fully at first!

**Pull request closed without merging**
