### PR TITLE
Improve dispatch popup and major-mode doc-strings

### PR DESCRIPTION
**Pull request by tarsius**
Just a suggestion. What do you think?

### CODE REVIEW

**Comment by npostavs** [comment]
I like the reorganization of the dispatch popup, but I'm not really sold on turning `describe-mode` into `describe-keybindings`.

**Comment by tarsius** [comment]
> I like the reorganization of the dispatch popup, but I'm not really sold on turning `describe-mode` into `describe-keybindings`.

Well, we already do that. This just adds the missing commands from section keymaps and presents the bindings that are explicitly listed in a different format.

**Comment by tarsius** [comment]
I just pushed to commits which modify `magit-dispatch-popup` and add `magit-file-buffer-{mode,popup}`. Rebasing this pr...

**Comment by tarsius** [comment]
a80751189a93b891362810eab8bac707745ec7f8 has to do it.

**Pull request closed without merging**
