### PR TITLE
magit-git-command displaying wrong process buffer

### PR DESCRIPTION
**Pull request by kyleam**
I'm not very certain of these changes, so please consider this a bug
report rather than a PR.

### CODE REVIEW

**Comment by tarsius** [comment]
The idea was to use one process buffer per repository, so we should not use `default-directory`, but always `(magit-toplevel default-directory)` (and I don't think it should be the callers who have to take care of this. Except of course when we are not inside a repository, if I remember correctly, we then use the global (usually startup) value of `default-directory`.

**Comment by kyleam** [comment]
> The idea was to use one process buffer per repository, so we should
> not use `default-directory`, but always `(magit-toplevel
> default-directory)`

OK.  I thought magit-git-command might be an exception because, if the
user is calling some git command from a subdirectory, the output may
depend on that directory, and it avoids running a command with a
different default-directory than the process buffer's default-directory.

I've pushed a second branch (km/command-subdir-2) that instead changes
magit-mode-get-buffer to compare its topdir argument with magit-toplevel
of the searched buffers.  This seems to work, while keeping everything
in the same process buffer, but perhaps it breaks things elsewhere.

**Comment by tarsius** [comment]
Maybe a compromise would be in order: use the top-level process buffer, but prefix the command in the header with the relative path `  0 lisp/$ git ...`.

**Comment by kyleam** [comment]
I like that idea.  Added to the km/command-subdir-2 branch.  Due to the face differences, I think it looks fine even without the "$".

**Comment by tarsius** [comment]
I have pushed minor terminology fixes to the v2 branch.

**Comment by tarsius** [comment]
I have installed v2 with some cosmetic changes. And one big change: the second commit was replaced with 4de98951c680b17d3806add121de2b0cfb8cf4c1.

**Comment by tarsius** [comment]
I had to revert 4de98951c680b17d3806add121de2b0cfb8cf4c1, but will try again later.

**Pull request closed without merging**
