### PR TITLE
git-rebase.el: Add new face to customize look of rebase actions

### PR DESCRIPTION
**Pull request by bastianbeischer**
- Add new face to customize look of "pick/reword/..." actions
- Fix group of git-rebase-comment-heading face

### CODE REVIEW

**Review by kyleam — CHANGES_REQUESTED** [review]
Thanks, changes look fine to me.  

Could you please move the `:group` correction for `git-rebase-comment-heading` into its own commit?

**Comment by tarsius** [comment]
The name of the face should not end with `-face' and the definition should not be placed in between two other faces which are clearly related to each other but not to the new face.

**Comment by tarsius** [comment]
> Could you please move the `:group` correction for `git-rebase-comment-heading` into its own commit?

I have just created that commit yourself. So you should rebase before you address the other feedback, @bastianbeischer.

**Comment by bastianbeischer** [comment]
Thanks for your comments! I updated the branch accordingly.

**Comment by tarsius** [comment]
Thanks!

**Pull request merged**
