### PR TITLE
Add --subject-prefix option to magit-patch-popup

### PR DESCRIPTION
**Pull request by andschwa**
Helps existing feature.

If this violates feature freeze, feel free to reject.

### CODE REVIEW

**Comment by tarsius** [comment]
It's okay to do things like this now. But in this particular case I have chosen to initially only add the most essential arguments. There are many more arguments all of which are used by someone but listing them all would be a bit overwhelming I'm afraid.

(On the other hand I've recently made some changes to the popup code, which would allow to better group arguments, so maybe I will reconsider. I always intended to go over this gain eventually anyway, but that is something I had scheduled for after the release).

For that reason  commit (63b55c1d5de677ef44e0375fb89af7a0f4471716) which added this popup contains:

> If I think that some important argument is missing, then please add it locally using `magit-define-popup-{switch,option}`.

In this case

```lisp
(magit-define-popup-switch 'magit-patch-popup %S "Subject Prefix" "--subject-prefix=" nil ?s)
```

**Comment by andschwa** [comment]
Oh cool! I didn't know I could do that, thanks :smile: 

I would still recommend including this on the menu when this popup-patch is gone back over, because the subject prefix is pretty frequently used in mailing list communities. I don't use format-patch or send-email without it!

**Comment by andschwa** [comment]
Yay Lisp.
``` elisp
(magit-define-popup-option 'magit-patch-popup ?S "Subject Prefix" "--subject-prefix=")
```
Gives me just what I needed.

**Comment by tarsius** [comment]
Ups, yes option, I have corrected my suggestion. You might want to keep the last two arguments.

**Pull request closed without merging**
