### PR TITLE
Use Emacs 27 ChangeLog generating function if available

### PR DESCRIPTION
**Pull request by npostavs**
This is an initial implementation for #2931, which uses the new ChangeLog generating functions I've written in [Emacs Bug#16301](https://debbugs.gnu.org/16301).

I'm not too sure about the setting of `rev1` and `rev2` in `magit-generate-changelog`. I tried to follow `magit-diff-while-committing` but I don't know if I really understood the logic there.

### CODE REVIEW

**Comment by tarsius** [comment]
I've actually also worked a bit on this a while back. Don't remember if it is any good but you might want to take a look at the `modified-defuns` branch.

**Comment by tarsius** [comment]
> I'm not too sure about the setting of `rev1` and `rev2` in `magit-generate-changelog`. 

Yeah. My version contains some code to deal with this but it is not actually being used and I don't think I considered it ready. I'll look into that.

**Comment by npostavs** [comment]
> take a look at the `modified-defuns` branch.

The `magit-diff--modified-lines` part is interesting, I didn't think of gathering the line numbers in a list; I used some local functions instead and it turned out more convoluted than I expected (I'm speaking of `diff-add-log-current-defuns` in the Emacs patch).

> Yeah. My version contains some code to deal with this but it is not actually being used and I don't think I considered it ready. I'll look into that.

After looking at this, I'm afraid I'm actually more confused than before. So I hope you can figure out what's needed here...

**Comment by tarsius** [comment]
Have you pushed the change to Emacs to some branch?

**Comment by npostavs** [comment]
I just pushed it to `master`: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=01661f33c11654d1fe5fe1013332db2500b7f449

**Comment by dickmao** [comment]
I'd like to submit https://github.com/dickmao/magit-patch-changelog as an alternative.

**Comment by npostavs** [comment]
> After looking at this, I'm afraid I'm actually more confused than before.

So I've taken another look at this, I believe the reason for my confusion was that I was trying to solve an impossible problem: there's no good way of deducing whether or not we're amending after the fact. I've made it controllable by prefix arg for now.

Comparing to @dickmao's `magit-patch-changelog`  solution:

- `magit-patch-changelog` avoids the problem mentioned above by restricting the command flow, so the user can't call the changelog generating function from the standard magit-commit command (i.e., `--amend` simply isn't an option).
- My solution is shorter because it relies on code I've added in Emacs 27, whereas `magit-patch-changelog` is longer and works in earlier Emacs versions.
- I also didn't think to implement anything like `magit-patch-changelog-xref`, that does seem quite nifty.
- `magit-patch-changelog` provides some fine-grained `magit-patch-changelog-agg-down` and `magit-patch-changelog-agg-up` commands, whereas my code expects the user to just write up the changelog and use `M-q` to aggregrate any adjacent empty entries all at once. I could see preferences going either way on this.

**Comment by dickmao** [comment]
I'm gratified someone, anyone, even looked at magit-patch-changelog.  I'm fairly sure no one uses it.

My feeling is the Changelog is a procedural relic of the past similar to TPS reports in form and dubious function, but so long as the emacs leadership continues to insist on it I suppose something ought to be done to make Changelog entries less like doing one's taxes.

**Comment by tarsius** [comment]
I've merged this. Who would have though.

I made some minor changes, which I did not push to the branch, so that they could be inspected.

Thanks @npostavs. And for your patience too. :grinning:

**Comment by npostavs** [comment]
To be honest, it was less patience specifically, and more that I haven't had much time to look at Emacs related stuff over the past months/year. I'm just starting to dig out now. :)

**Comment by tarsius** [comment]
Welcome back!

**Pull request closed without merging**
