### PR TITLE
rebase mode: move line extensions

### PR DESCRIPTION
**Pull request by kyleam**
See #2412.

### CODE REVIEW

**Comment by npostavs** [comment]
The multiple lines selection feels a bit weird, should we add magit's special region-composed-of-lines highlighting here too?

**Comment by kyleam** [comment]
Thanks for the fixups.

> should we add magit's special region-composed-of-lines highlighting here too?

I think it's worth trying out.  I'll have a look.

**Comment by kyleam** [comment]
OK.  I've added a commit that uses magit-section-heading-selection
instead of the normal region.  I'm sure there are places that could be
cleaned up, but it seems to be working.  WDYT?  Worth it?

**Comment by tarsius** [comment]
I came here to say "please keep the lines selected after moving them", but that already works!

Please merge once you feel this is ready. Looks good to me.

**Comment by npostavs** [comment]
> OK. I've added a commit that uses magit-section-heading-selection
> instead of the normal region.

Shouldn't the body of `git-rebase-update-highlight` go in `git-rebase-highlight-region` and then a `post-command-hook` is not needed?

**Comment by kyleam** [comment]
> Shouldn't the body of git-rebase-update-highlight go in git-rebase-highlight-region and then a post-command-hook is not needed?

Yeah, I guess I was trying to follow magit proper too closely.  Your suggestion seems to work well.

**Comment by kyleam** [comment]
Updated.  I'll merge after waiting a bit for any other comments.

**Comment by tarsius** [comment]
Please mention this in the release notes.

**Comment by npostavs** [comment]
I added a bit more simplification fixup.

My only remaining concern is that I think `magit-section-heading-selection` is a bit hard to see, at least with default (`emacs -Q`) colours.

**Comment by kyleam** [comment]
> I added a bit more simplification fixup.

Thank you.

> My only remaining concern is that I think
> magit-section-heading-selection is a bit hard to see, at least with
> default (emacs -Q) colours.

Hmm, is there another magit selection face that you think we should
switch it to?  I went with magit-section-heading-selection because
it's the one used for log lines, which seems the closest match for
lines in the rebase buffer.

**Comment by kyleam** [comment]
> Please mention this in the release notes.

Done.

**Comment by tarsius** [comment]
> Hmm, is there another magit selection face that you think we should switch it to?

I would say you are using the right face. But maybe that face's default value ain't no good. I don't know, I haven't looked at the default theme for quite a while.

**Comment by kyleam** [comment]
> I would say you are using the right face. 

OK, I've merged this then, since changing the default for that face is a separate issue.

**Pull request closed without merging**
