### PR TITLE
Don't use log's file restriction with --follow

### PR DESCRIPTION
**Pull request by kyleam**
Please see commit messages.

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks! That was bothering me too.

**Comment by tarsius** [comment]
We should probably find a key for magit-revision-toggle-file-filter. Maybe `f` in `magit-diff-refresh-popup`?

**Comment by tarsius** [comment]
... after generalizing it as `magit-diff-toggle-file-filter`.

**Comment by kyleam** [comment]
> We should probably find a key for magit-revision-toggle-file-filter. Maybe f in magit-diff-refresh-popup?

Sure, `f` sounds good to me.

> ... after generalizing it as magit-diff-toggle-file-filter.

That also makes sense.  I'll look into it.

**Comment by tarsius** [comment]
Off topic: Is `magit-imerge` ready for Melpa? (If so I can add it. That's easier because I don't have to go through the review process.)

**Comment by tarsius** [comment]
Ups, `f` is taken. Maybe `F`.

**Comment by kyleam** [comment]
> Ups, f is taken.

Not by an action though.

**Comment by kyleam** [comment]
Yeah, I think `magit-imerge` is ready for MELPA.  I was holding off to
see if I got any feedback from imerge users, but that probably won't
happen until it's on MELPA :)

> If so I can add it. That's easier because I don't have to go through the review process

Thanks, that'd be great.  Just a heads up: I haven't run
`package-lint` on it.

**Comment by tarsius** [comment]
Not in revision and status buffers, but in diff buffers it is. It flips revisions.

**Comment by kyleam** [comment]
> Not in revision and status buffers, but in diff buffers it is. It flips revisions.

Doh, indeed.  I should know that :)

**Comment by tarsius** [comment]
> Doh, indeed. I should know that :)

Don't feel bad. I think I was looking at the **log** popup before suggesting `f` :wink: 
Time for bed.

**Comment by tarsius** [comment]
```
1 issue found:

9:39: error: Package magit is not installable.
```

Looks like I have to teach `package-lint` about `borg`.

**Comment by tarsius** [comment]
Where nicely alternating between the two topics... I think next time I will send a mail :smile_cat:

**Pull request merged**
