### PR TITLE
Add `magit-bisect-start-and-run`

### PR DESCRIPTION
**Pull request by Silex**
See #2290 

Quickly pulled together, but seems to work.

### CODE REVIEW

**Comment by Silex** [comment]
Btw, why not `s` for `skip`? Maybe as an alias?

Also, `a` for run is pretty bad... maybe `n`?

**Comment by tarsius** [comment]
> Also, `a` for run is pretty bad...

I am guessing it stands for "automatically".

**Comment by tarsius** [comment]
I think I would prefer to do it like this: https://github.com/magit/magit/compare/jb/bisect-run?expand=1. That's more in line with what I intended to do all along.

**Comment by Silex** [comment]
Hum, what if I already started a session? I think your commit just lacks the binding for `magit-bisect-run` in the 2nd popup and otherwise looks nice.

**Comment by tarsius** [comment]
Ah so my original intention must have been to *only* offer `run` when starting to bisect. It's not how `git bisect` does it, but I feel it makes sense.

**Comment by npostavs** [comment]
> Ah so my original intention must have been to *only* offer `run` when starting to bisect. It's not how `git bisect` does it, but I feel it makes sense.

I'd prefer to have `run` available after starting too. Sometimes I need a few interactive "practice" runs before I'm ready to let the script run by itself. And sometimes I need to a few interactive runs before I realize I should really be using a script. It would be nice if these scenarios didn't require restarting the bisect session.

**Comment by tarsius** [comment]
Makes sense.

So what should the key bindings and the descriptions be?

**Comment by npostavs** [comment]
I think @Silex's descriptions are fine, but `Start & Run` and `Run` should be on the same key. I don't have a strong preference for `R` vs `a`, I guess `R` is a bit more memorable.

**Comment by tarsius** [comment]
We use `B` for the default action because `BB` is nicer than `Bb`. We do the same for other popups too. But for `run` we should use `Br` (or `Ba`), again like we do for other popups.

**Comment by Silex** [comment]
I agree that `Start & Run` and `Run` should be on the same key. I think `BR` makes more sense because it's easier to type & remember, and it implies that it's an action a bit different (more "final"), just like `bB` is for branches. 

I looked at few popups and uppercase/lowercase consistency didn't seem to be such a strong rule (e.g `PQ` `TS` `bB`), but tbh I don't care really much, whatever bindings I'll be happy with as long as it's fixed :)

**Comment by npostavs** [comment]
> but tbh I don't care really much, whatever bindings I'll be happy with as long as it's fixed :)

Yeah, it's not a thing one uses often enough to develop a muscle memory for.

Anyway, I pushed commits [jb/bisect](https://github.com/magit/magit/compare/jb/bisect-run?expand=1) to use `Ba` both before and during bisection. `Br` could work but then we have to decide what "Reset" should be.

**Comment by Silex** [comment]
Looks good to me.

**Comment by tarsius** [comment]
I have pushed my (improved) version to `master` and am closing this. If you disagree with the descriptions and keys I have picked we can still change them.

**Comment by Silex** [comment]
Thanks!

**Pull request closed without merging**
