### PR TITLE
magit-gitk-executable: fix runtime error when gitk is not installed

### PR DESCRIPTION
**Pull request by kostya-sh**

### CODE REVIEW

**Comment by tarsius** [comment]
Hehe. Either a big coincidence or something changed in a new Git release: #3455.

**Comment by tarsius** [comment]
Actually, you might beat @bennorth to it.

What @npostavs suggests there is that the outer `or` be replaced with an `if`.

**Comment by tarsius** [comment]
Hm, @bennorth looked at the issue in more detail, so I prefer their commit message.

**Comment by npostavs** [comment]
> What @npostavs suggests there is that the outer or be replaced with an if.

Actually, I didn't mean for the outer `or` to change, just to add an `if` around the `and`.

**Comment by kostya-sh** [comment]
Glad that this is now fixed! https://github.com/magit/magit/pull/3455 is a great coincedence indeed ;)

**Pull request closed without merging**
