### PR TITLE
WIP always show revision header but make it selectable

### PR DESCRIPTION
**Pull request by tarsius**
Display the same information in the `header-line` and the first line
of the buffer text, but make sure only one of them is every actually
displayed.

When the `window-start` is visible, then don't show the `header-line`.

There are still some minor issues, but I generally like it.

### CODE REVIEW

**Comment by kyleam** [comment]
Once the fringe is accounted for, I think the transition will seem
pretty seamless.  One place where this breaks down is is calling
beginning-of-buffer at the end of a scrolled buffer, which results in
two hash lines until the next command is given.  (I'm not sure why
post-command-hook doesn't catch this case.)

**Comment by npostavs** [comment]
> One place where this breaks down is is calling
> beginning-of-buffer at the end of a scrolled buffer, which results in
> two hash lines until the next command is given. (I'm not sure why
> post-command-hook doesn't catch this case.)

I'm also seeing it fail if I call `next-line` when point is on the bottom line of the window. Maybe the post-command-hook sometimes runs before the display updates??

But when it works, it's hardly noticeable, not annoying at all.

**Comment by tarsius** [comment]
Pushed an update with the flickering fixed. I had to add two pixels to the fringe-width, I hope that's a constant value.

I see two more issues:

* The fringe is shown. But that could be considered a feature as it makes it more likely that one notices that the line can be entered.

* If the face has the `:underline` property set, then that is not used for the complete line, even if the trailing newline is also propertized.

We should probably take these issues to the stackexchange site.

> Conjecture: it works with scrolling commands and fails with point movement commands because point movement triggers scrolling only later in the command loop.

That brings back bad memories...

Is there another hook we could use. Some post motion hook. Or are they triggered at the wrong time too?

**Comment by kyleam** [comment]
Hmm, also seems to break for magit-diff-show-or-scroll-up.

**Comment by tarsius** [comment]
Unlikely this will  be done in time for `2.2.0` then.

**Comment by npostavs** [comment]
Using `window-scroll-functions` seems to work:

```diff
diff --git i/lisp/magit-diff.el w/lisp/magit-diff.el
index 6367f3c..96b5956 100644
--- i/lisp/magit-diff.el
+++ w/lisp/magit-diff.el
@@ -1320,12 +1320,12 @@ (define-derived-mode magit-revision-mode magit-diff-mode "Magit"
 Type \\[magit-reverse] to reverse the change at point in the worktree.
 \n\\{magit-revision-mode-map}"
   :group 'magit-revision
-  (add-hook 'post-command-hook 'magit-revision-hideshow-header-line nil t)
+  (setq-local window-scroll-functions #'magit-revision-hideshow-header-line)
   (hack-dir-local-variables-non-file-buffer))
 
-(defun magit-revision-hideshow-header-line ()
+(defun magit-revision-hideshow-header-line (window window-start-pos)
   (setq header-line-format
-        (and (not (pos-visible-in-window-p 1))
+        (and (> window-start-pos 48)
              (concat
               (propertize " " 'display
                           `((space :width (,(+ (car (window-fringes)) 2)))))
```

Note: I thought we're supposed to use `add-function` for `*-functions` type variables, but when I do `(add-function :after (local 'window-scroll-functions) #'magit-revision-hideshow-header-line)` Emacs tries to `(apply nil ...)` when running the `window-scroll-functions` so I just used `setq-local` instead.

**Comment by kyleam** [comment]
Using `window-scroll-functions` seems to be working nicely.

**Pull request closed without merging**
