### PR TITLE
Fix documentation typos and grammar

### PR DESCRIPTION
**Pull request by danielmai**
- Update some typos, such as "to" to "too"
- Update grammar where appropriate, such as commas and verb conjugation
- Update to name spelling, such as Git and TRAMP

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks!

**Comment by kyleam** [comment]
The applied change (7ca824f3d) doesn't match the commit message.  It
only consists of a single change (`s/bound/bind/`) in magit.texi.
(That typo was actually already fixed in 32e5cb832, but magit.texi
wasn't regenerated.)

@danielmai Presumably this means that you still have various fixes for
the manual that are not yet in master?

**Comment by tarsius** [comment]
No, I think it means that I messed up something somehow. Will try to recover from reflog.

**Comment by kyleam** [comment]
> No, I think it means that I messed up something somehow.

Right, that could very well be the reason why he still has fixes
locally that aren't in master.  I was focusing on the end result
because I don't know whether the issue was submission or application :)

**Comment by tarsius** [comment]
Fixed. The rest can be found in 08ee370dac5f98a9d70f51fce4566442312ff706 :blush:

**Comment by tarsius** [comment]
Huh? What is going on? Reverting that commit.

**Comment by tarsius** [comment]
Ah! @danielmai You edited only `magit.texi`, right? You should instead edit `magit.org` and we will then regenerate `magit.texi` from that and amend it to your commit. That would explain why my amending attempts ended up removing your changes again.

**Comment by tarsius** [comment]
Please port your changes over to `magit.org` and open a new pull request.

**Comment by danielmai** [comment]
Oops, I didn't know that magit.org was the source of truth. I'll open another pull request with the correct changes. Thanks @tarsius and @kyleam.

**Pull request merged**
