### PR TITLE
Add support for git reset --keep

### PR DESCRIPTION
**Pull request by jdelStrother**
I use `git reset --keep` a lot from the command line when I have some uncommitted changes that I realize ought to be applied to a different branch.  How about something like this in magit?

I'd welcome any suggestions that would make the wording clearer.

### CODE REVIEW

**Comment by tarsius** [comment]
Maybe just `(HEAD and index, keep uncommitted)`, because it is shorter.

**Comment by jdelStrother** [comment]
OK, updated.

**Comment by tarsius** [comment]
Please also update the manual. (Just the org file. I can update the texi).

**Comment by tarsius** [comment]
Thanks!

I've changed some metadata and whitespace.

**Pull request merged**
