### PR TITLE
ediff  range changes

### PR DESCRIPTION
**Pull request by kyleam**
This is part of the #2035 discussion not a PR.

### CODE REVIEW

**Comment by kyleam** [comment]
I've pushed updates.  The main addition is that magit-diff and magit-ediff-compare now use the dwim-context to generate the prompt defaults.

**Comment by kyleam** [comment]
Here's a summary of the difference in behavior between magit-ediff-dwim on master versus the tip of this branch.

```
| dwim context                          | old (, default)           | new                         |
|---------------------------------------+---------------------------+-----------------------------|
| commit                                | prompt, commit^..commit   | commit^..commit             |
| branch, not current, not tracked      | prompt, branch^..branch   | branch..current             |
| branch, current with upstream         | prompt, current^..current | upstream...current          |
| branch, current, working tree changes | prompt, current^..current | current with working tree   |
| branch, current                       | prompt, current^..current | current^..current           |
| unstaged, staged hunk                 | magit-ediff-stage         | magit-ediff-stage or show + |
| unpulled header                       | current..upstream         | current...upstream          |
| unpushed header                       | upstream..current         | upstream...current          |

+ depending on value of magit-ediff-dwim-show-on-hunks

```

**Comment by tarsius** [comment]
Sorry for the delay, I have been busy with other things. I'll have a look soon. Do you consider this "done"?

**Comment by kyleam** [comment]
> Sorry for the delay, I have been busy with other things. I'll have a
> look soon.

No problem.  Whenever you get a chance.

> Do you consider this "done"?

Yes, I don't have any plans to add more to this series and think it's
ready for review.

**Comment by tarsius** [comment]
Before merging I have rebased, rearranged the popup actions, and made some cosmetic changes (mostly whitespace). Thanks again, this is really nice.

**Comment by tarsius** [comment]
Could you please also update the manual. Most importantly list the new commands and options in the appropriate sections. Thanks.

**Comment by kyleam** [comment]
Thanks.  I'll update the manual for this and also #2010.

**Comment by tarsius** [comment]
I have added a release note stub. Please mention these changes there too.

**Pull request closed without merging**
