### PR TITLE
Reverse in index

### PR DESCRIPTION
**Pull request by npostavs**
As discussed in #2330, the workflow for splitting commits requires a double reversal that can be done in a single step, which is quicker and simpler. The main difficulty is how to name and bind the command.

Initially I thought of putting it in the revert popup.
Another idea is to bind to `u` for committed changes (instead of user-error "can't unstage committed changes"). In patch here I've co-opted the unstage command, I couldn't quite see how to change the binding, would we need an unstage-thing command and then remapping in the section keymaps (but committed hunks are the same section type as uncommitted ones, so we migh have a problem there)?

For naming I started with `magit-reverse-index`. I also thought of `magit-anti-stage` (too cryptic? although @MikeSanMichel2 did independently come up with "Stage Anti-Hunk" as a label).

### CODE REVIEW

**Comment by npostavs** [comment]
Continued from #2330.

> I can't think of a scenario where my next step wouldn't be "C e".

You might want `C a` to change the commit message to reflect the changed you just removed. Also, if the change you want to split out is spread over a few hunks it's nicer if you're not forced to commit the reversal of each one.

> "Revert Hunk"/"Stage Hunk for Removal"/"Stage Anti-Hunk"?

We already have "Revert", which is slightly different. I did think of "Anti Stage" which is a bit like your "Stage Anti-Hunk" (note that this command is not confined to whole hunks, it's it's just a modified call to `magit-reverse` so it works on files and regions (parts of hunks) too).

**Comment by MikeSanMichel2** [comment]
I think `magit-reverse` should definitely be represented in `magit-revert-popup`, as a command (or several).

From just a few hours of playing with this, it seems very useful to have at least a variant of the command that "C e" immediately. You can always use the smart commit commands
to perform extra steps in the familiar way. One advantage of bundling the "C e" into the action is that it makes for a simpler concept. It is simply "Uncommit".  That's just my (strong) preference
based on how I work, but It simply be an option with whatever default you prefer (Just as long as I can override with what **I** prefer).

Also, I understand (now) that `magit-reverse` isn't limited to hunks, I just think that's the coolest part about it  (except perhaps uncommitting range selections). Today, after reading the docs again and what the wiki had to say about it (utterly incomprehensible) I feel this is a kickass feature that most people will have little chance of discovering with going to great lengths.
That's why a name like "Uncommit hunk" seems so attractive. But, I admit it's not wise to limit a general command to a specific case in the popup for just that reason. Still, I think something like
that would really benefit users, maybe you have a better idea how to go about this?

**Comment by npostavs** [comment]
I added `magit-uncommit-extend` which does anti-stage and then commit-extend, bound to `V e`. It occurred to me that the other revert commands also commit directly, so bundling the commit action makes it closer to them.

> Otherwise, explaining how the commit really isn't affected, but you now have an electron in your working directory and its positron in the index, and that you need to "C e", to annihalate with part of the cherry-picked commit, so it can become the new, modified, cherry-picked commit? I mean, that's just pedagogically cruel.

But also hilarious :D

**Comment by MikeSanMichel2** [comment]
Cool. I think it only makes sense to have duals (turtles?) all the way down:
```
edit file
    stage change
        commit change
        uncommit change  <--- only this is/was missing, and it deserves to be a first-class operation
    unstage change
undo edit
```

**Comment by tarsius** [comment]
I haven't read up on all the above yet, but let me start by saying that I think this should be an action, not a switch. As far as I can tell so far, you seem to agree and the switch-idea was... well just an idea.

**Comment by MikeSanMichel2** [comment]
Glad to hear it. I'm still in favor of "Uncommit (foo)".
`commit` moves things from index to history, so moving something from history to index is logically an `Uncommit`. That's what "extract and extend" does, without the implementation detail of the anti-hunk  and amend step.

**Comment by tarsius** [comment]
> Initially I thought of putting it in the revert popup. Another idea is to bind to `u` for committed changes (instead of user-error "can't unstage committed changes").

This is only my tentative opinion: Adding to the popup seems like a good idea, but we should probably *also* provide a top-level binding. I don't like the idea of overloading unstaging, I would like to keep the "apply variants" pure. Users are already having problems telling some of the variants apart in their pure form - overloading is only going to make matters worse. In the past "reverse" did fallback to "discard" in places where "reverse" did not make sense. I removed that because "reverse" and "discard" are very different actions and while "reverse" is harmless, "discard" it quite dangerous. We still get complains about the removal of that fallback. I don't want something similar to happen with "unstage" and "'anti-stage'".

So maybe we could use `K` or something.

**Comment by npostavs** [comment]
> commit moves things from index to history, so moving something from history to index is logically an Uncommit

`commit` doesn't remove things from the index though, whereas your proposed Uncommit remove things from the history so it's not quite symmetric (not necessarily a problem with that though).

> I don't like the idea of overloading unstaging, I would like to keep the "apply variants" pure

Actually I don't really like it either, I wanted to overload the *key* `u`, but that requires splitting the "hunk" section type into "committed hunk" and "uncommitted hunk". Even overloading the key could cause confusion though.

> So maybe we could use K or something.

`K` is `magit-file-untrack` (though that command would not be used often anyway, does it even deserve a 1 key binding?).
Unused bindings: `C` (unCommit?), `H`, `N`, `O`, `Q`.

**Comment by npostavs** [comment]
> uncommit change <--- only this is/was missing, and it deserves to be a first-class operation

There are many more possible operations than in your diagram. I was attempting to enumerate them, when I noticed that your uncommit is actually very similar to mixed reset, the only difference being that uncommit works on hunks, whereas reset is restricted to whole commits. Perhaps this can inform our decision with respect to binding and naming. (it made me notice I missed `X` (and a few others) in my list of free bindings (which I've edited now)).

**Comment by MikeSanMichel2** [comment]
>  > commit moves things from index to history, so moving something from history to 
> > index is logically  an Uncommit
>
> commit doesn't remove things from the index though, whereas your proposed Uncommit remove 
> things from the history so it's not quite symmetric (not necessarily a problem with that though).

commit doesn't remove anything from the *working directory*, but it sure enough clears the index. 
You are right in that what I'm calling "Uncommit" should also stage the extracted hunk after
the commit is extended with the anti-hunk (In the special case where magit-reverse was applied to a hunk and not a commit).

To be clear, let's spell "uncommit" out. Defining "state" as `working directory`+`index`+`history/log`:

```
touch foo
git add foo  <- let's call the state after this step S1
git commit -m "foo"
uncommit <- let's call the state after this step S2
```

The operation I'm calling Uncommit would `assert(S1==S2)`, when `magit-reverse` is performed
at the granularity of a whole commits. If a single hunk (From several) was uncommited, it dwim's.

I agree more operations are possible, but this feels fundamental to me. The rest are just
that + (some other steps).

**Comment by npostavs** [comment]
> commit doesn't remove anything from the working directory, but it sure enough clears the index.

This may be an overly implementation centric perspective, but the index is not cleared: index stays the same, while it's changes are added to HEAD so that the *difference* between the index and HEAD becomes nil.

> To be clear, let's spell "uncommit" out.

Right, I was slightly confused in my previous post, it's like soft reset, not mixed.

**Comment by MikeSanMichel2** [comment]
Right. we mean the same thing and you're technially correct. The outcome nonetheless is that index contains no pending (staged) changes.

**Comment by npostavs** [comment]
Okay, so we have "uncommit" which is like a partial soft reset to HEAD, and "reverse in index" (aka "anti-stage") which is like a partial `(magit-reset-index HEAD)`.

How about `magit-reset-{soft,index}-dwim` commands which do the partial variants when on a committed change, and ask for a commit (as a reset target) otherwise? `magit-reset-soft-dwim` could be sensibly bound to `X`. We could leave `magit-reset-index-dwim` unbound, like `magit-reset-index`:

https://github.com/magit/magit/issues/2296#issuecomment-143867557

> The default should be what most users would expect, they shouldn't have to change a key binding to get that, and advanced users can get the advanced variant by changing a key binding.

**Comment by MikeSanMichel2** [comment]
Well, I've been using git for 5 years? a decade? and I've never thought of `reset --soft` as `uncommit` before.  Much easier to grok, but I suppose remaining true to git is more important given how
many concepts it introduces by itself. Forking the names is a bad long-term strategy.

**Comment by npostavs** [comment]
We could provide `uncommit` by itself, and bind that to `X`. `magit-reset-soft` would remain unbound, as it is now, so nothing is lost. The dwim type can be tricky, maybe they're better off avoided.

`reset --soft` isn't *exactly* the same as `uncommit` in all cases, but they do share some common ground.

**Comment by MikeSanMichel2** [comment]
You need to be conservative about rechristening things when there are so many, but this is about the revert popup and the reset commands don't live here. So I guess this is legitimate. the user doesn't need to know how it is implemented or what it's equivalent to.

If this was a `reset` popup, *then* calling `--soft` by any another name would be a no-no.

**Comment by npostavs** [comment]
> No, seriously, why isn't rebase continue r c?

`r r` is easier to type.

**Comment by Silex** [comment]
>> No, seriously, why isn't rebase continue r c?

> r r is easier to type.

... and it follows the "most common operation" logic, like `c c`, `F F`, `P P` and all the others.

**Comment by MikeSanMichel2** [comment]
> >   No, seriously, why isn't rebase continue r c?
> r r is easier to type.

so why isn't skip `r t`?

**Comment by Silex** [comment]
> so why isn't skip r t?

Because that is not easy to type.

**Comment by MikeSanMichel2** [comment]
okok, makes no sense but not what this issue is about.

**Comment by Silex** [comment]
> The c in c c stands for Commit. The P in push stands for Push. I have no idea what F does.

So you never `pull`?

> okok, makes no sense but not what this issue is about.

Well, you're the one over-focusing on these keybindings :) They make perfect sense when you consider classic workflows.

**Comment by MikeSanMichel2** [comment]
There aren't many pieces of software I care anough to argue about keystorkes. magit is pretty special.
Believe me, I can argue this with you for a long time, but let's not kill this thread. erasing in 5...4..

**Comment by npostavs** [comment]
> the user doesn't need to know how it is implemented or what it's equivalent to.

Hmm the current implementation would also commit any unstaged changes.

**Comment by tarsius** [comment]
I am not so sure the proposed commands are a good idea - they could be rather confusing. Feel free to keep experimenting if you disagree and I might change my mind when I see the end result.

But we should now concentrate on the remaining bugs, such as #2309. I would like to release v2.3.0 soon and hope that we can fix all known bugs before then.

**Comment by MikeSanMichel2** [comment]
@Silex, I removed my offtopic comments would you mind doing the same for your resopnses? I don't  to hijack @npostavs's thread.

**Comment by MikeSanMichel2** [comment]
@silex, since you won't remove your comments I might as well repond.

> >    The c in c c stands for Commit. The P in push stands for Push. I have no idea what F does.

> So you never pull?

That's right, not with magit. I somehow naturally always switch to shell when I want to pull.  It's mostly unconcious (I haven't actually noticed that I don't use magit for that), but I realize now this is because of #1485,  and why I always specify the remote I'm pulling from.

> >    okok, makes no sense but not what this issue is about.

> Well, you're the one over-focusing on these keybindings :) They make perfect sense when you 
> consider classic workflows (ease of continuing with the most common scenario).

That's a matter of taste. All other keybindings generally match the first letter of their operation and I find it easier to think of "(r)ebase (c)ontinue" as "r c" just as I think of "(r)ebase (a)bort" as "r a". But since magit lets you customize it however you want (I now have), this isn't a problem.

**Comment by tarsius** [comment]
So this doesn't appear to be in popular demand.

**Comment by npostavs** [comment]
I do still intend to implement this at some point, IMO just looking at [History-Manipulation][h] it's clearly needed.

[h]: https://github.com/magit/magit/wiki/History-Manipulation

**Comment by tarsius** [comment]
Alright.

**Comment by tarsius** [comment]
For the time being I have added these commands to the `magit-rockstar` package.

**Pull request closed without merging**
