### PR TITLE
Add new hook magit-ediff-quit-hook

### PR DESCRIPTION
**Pull request by tarsius**
See #1963 and c18264374d1a42edfc7e781a8c7fe39d78b4ea1b.

Please test and comment.

### CODE REVIEW

**Comment by michael-heerdegen** [comment]
Thanks!  That looks appropriate and solves by problem.

Two comments:

1.

> +(defvar smerge-ediff-buf)
> +(defvar smerge-ediff-windows)

I guess it's not good to reuse prefixes from different packages.  I would call it "magit-smerge-..."

2.
```
(defcustom magit-ediff-quit-hook
  '(magit-ediff-cleanup-auxiliary-buffers
    magit-ediff-restore-previous-winconf)
  ...)
```

Caveat: Filling hooks via variable definition can be problematic: If the user does "add-hook" to the variable before loading the definition (i.e. before requiring the package), the specified hook members will not become part of the hook (because the variable's value will not be touched).

AFAIK there is no perfect solution to this problem, but using a default value of nil and adding to the hook afterwards might be better.  A user wanting to setq the hook can still use "with-eval-after-load".

P.S.  I really hope you can switch to lexical binding soon and get rid of all these backquoted lambdas.

**Comment by tarsius** [comment]
> I guess it's not good to reuse prefixes from different packages. I would call it "magit-smerge-..."

Magit only used the values of these variables, it is Smerge which sets it. Smerge should properly define these variables but unfortunately it does not, so we have to declare them to avoid compile warnings.

> Filling hooks via variable definition can be problematic:

This is being done a lot in Emacs too, so I am going to stick with this.

> I really hope you can switch to lexical binding soon and get rid of all these backquoted lambdas.

I intend to do it eventually, but am not in a hurry :-)

> solves by problem.

Could you please post your configuration. I am considering to use a new frame too.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> Magit only used the values of these variables, it is Smerge which sets
> it. Smerge should properly define these variables but unfortunately it
> does not, so we have to declare them to avoid compile warnings.

smerge-mode.el devfar's them in Emacs master.  But I guess you
nonetheless need to quite the byte compiler.

> Could you please post your configuration. I am considering to use a
> new frame too.

I wouldn't call it a configuration but a hack.  Anyway, don't you think
this should better be done in Ediff itself?

**Comment by michael-heerdegen** [comment]
Anyway, here is my setup for using pop-up frames:

```
(defun my-ediff-setup-windows (&rest args)
  (let ((oframe (selected-frame))
	(frame (make-frame)))
    (select-frame-set-input-focus frame)
    (set-frame-parameter frame 'ediff-frame oframe)
    (apply #'ediff-setup-windows-plain args)
    (set-frame-parameter nil 'fullscreen 'maximized)
    (run-with-idle-timer
     0 nil
     (lambda ()
       (when (and (window-live-p ediff-control-window)
                  (not ediff-use-long-help-message))
         (minimize-window ediff-control-window))))))

(setq-default
 ediff-window-setup-function 'my-ediff-setup-windows
 ediff-split-window-function 'split-window-horizontally)

(defun my-ediff-quit-dwiw ()
  "Do what I want after quitting ediff."
  (let* ((current-frame (selected-frame))
	 (oframe (frame-parameter current-frame 'ediff-frame)))
    (when oframe
      (other-frame 1)
      (sit-for 0)
      (delete-frame current-frame)
      (sit-for 0)
      (when (frame-live-p oframe)  (select-frame-set-input-focus oframe)))))

(add-hook 'ediff-quit-hook #'my-ediff-quit-dwiw 'append)
(add-hook 'magit-ediff-quit-hook #'my-ediff-quit-dwiw 'append)
```

Unfortunately one can't get rid of timers and sit-for's because you have to wait until the frames are created or deleted "physically".

**Comment by tee3** [comment]
This seems to work for me, `ediff-cleanup-mess` still runs and cleans up properly.

**Pull request merged**
