### PR TITLE
Underline using :align-to

### PR DESCRIPTION
**Pull request by tarsius**
Open pr so that we have a place to talk about it. Edit: for previous discussions see #2094.

If Eli says one should not use newlines in overlays then we should try to follow his advise but unfortunately I have run into several issues with his approach too, which are just as much beyond our control as the issue with the old newline-approach, which I fixed for us. We might end up having to ask him for workarounds to be able to follow his advice.

Since the current approach works and I want to get a release out, I see no reason to rush this. But I would like to work with Eli to address the issues that are coming up here - they have bothered me in different contexts before.

There also were two issues with you implementation which I addressed in v2. When both the overline and the underline overlays were on the same line, then the underlining did not work. And you didn't account for pixel-wise resizing of windows.

### CODE REVIEW

**Comment by npostavs** [comment]
Not sure exactly what you meant by "blows up", but assuming it's the addition and removal of the newline following the header it should be fixed by b30aec92a64cd277ae61315cfef2de8be815a1b6.

I've noticed another glitch though: doing `C-e` (`move-end-of-line`) goes to the window's end instead of the line's end. Or perhaps more accurately, the end of line is pushed to rightward to the end of window, causing various changes with point movement around there.

**Comment by tarsius** [comment]
I wonder, despite Eli's arguments, if we only want to change how things look, wouldn't it then maybe be best if we did just that ;-)

**Comment by tarsius** [comment]
Or kindly ask him to implement `(space :align-to 'the-visible-edge-of-the-window)`.

**Comment by npostavs** [comment]
> I've noticed another glitch though: doing C-e (move-end-of-line) goes to the window's end instead of the line's end.

Fixed that, but there's still some weirdness with `C-n` when point is at the end of line.

**Comment by npostavs** [comment]
Eli fixed a bug where truncated lines with the overlay would cause `end-of-line` to skip a line, but there is still a minor glitch where the temporary-goal-column gets set to the windows' right edge instead of eol, when point is at eol. Eli won't fix that.

>This is not a bug: vertical-motion doesn't know about the 'cursor'
property, so it works as if the property didn't exist.
[...]
> I think a casual mismatch in a column while moving
through a buffer, and in marginal cases at that, is not a big deal.

He also says the overlay with newline approach will likely cause more, as yet uncovered, problems

> I'm quite sure problems will surface sooner or later.  Overlays with
newlines hit on fragile parts of the display engine code, which was
never really designed for that kind of stuff.

---

So we have to decide if a little glitch (or 2 on Emacs 24) is worth (hopefully) avoiding potential future problems. I'm leaning towards yes, because I don't think the glitches will be triggered in typical uses of the region.

**Comment by tarsius** [comment]
I lean toward let's keep what is working now until it starts breaking. We should however have a patch ready for when it does start breaking.

**Comment by tarsius** [comment]
Lets keep it ready (branch) but not pending (pull request).

**Pull request closed without merging**
