### PR TITLE
Improve performance of `magit-insert-recent-commits`

### PR DESCRIPTION
**Pull request by vermiculus**
Related to my investigation in #2982.

See commits for details.

### CODE REVIEW

**Comment by tarsius** [comment]
We've added the range in 55a61d15e85fe46409e512cc60815e61b4843066.
To improve performance! :scream:

**Comment by vermiculus** [comment]
Fascinating! Your explanation in that commit message makes good sense. Should this optimization be made conditional on whether `--graph` is in the argument list?

**Comment by tarsius** [comment]
> Should this optimization be made conditional on whether `--graph` is in the argument list?

Maybe, though such a solution might depend on the user knowing that this is a bottleneck and that disabling that argument is needed.

I'll experiment with this eventually, but currently I trying to get some other things done. I don't have access to a humongous monorepo, so maybe you could run some benchmarks. (Using `time git log [all the variants]` outside of Emacs, should be good enough for our needs).

**Comment by vermiculus** [comment]
To be specific, 'all the variants' here means at least the following, right?

```
time git --no-pager log --oneline -n10 --graph HEAD
time git --no-pager log --oneline -n10 --graph HEAD~10..HEAD
time git --no-pager log --oneline -n100 --graph HEAD~100..HEAD
time git --no-pager log --oneline -n10 HEAD
time git --no-pager log --oneline -n10 HEAD~10..HEAD
time git --no-pager log --oneline -n100 HEAD~100..HEAD
time git --no-pager log --oneline --graph HEAD
time git --no-pager log --oneline --graph HEAD~10..HEAD
time git --no-pager log --oneline --graph HEAD~100..HEAD
time git --no-pager log --oneline HEAD
time git --no-pager log --oneline HEAD~10..HEAD
time git --no-pager log --oneline HEAD~100..HEAD
time git --no-pager log --oneline -n10 --graph
time git --no-pager log --oneline -n100 --graph
time git --no-pager log --oneline -n10
time git --no-pager log --oneline -n100
time git --no-pager log --oneline --graph
time git --no-pager log --oneline
```

I'll have that shortly. Based on how long I've been in `-n100 --graph` is taking, it may be a while.

It struck me while watching the christmas tree that is `--graph` output that `HEAD~10..HEAD` is not necessarily ten commits. There's probably not a safe way to be more restrictive about that range.

**Comment by vermiculus** [comment]
Turns out it wasn't `-n100 --graph` that was taking a while; it was `--graph HEAD` *facepalm* Churned through **>40GB** of memory before the terminal died.

Results are in:

```
git --no-pager log --oneline -n10 --graph HEAD             0.08s user 0.11s system 26% cpu 0.702 total
git --no-pager log --oneline -n10 --graph HEAD~10..HEAD    0.06s user 0.04s system 88% cpu 0.106 total
git --no-pager log --oneline -n20 --graph HEAD~20..HEAD    0.15s user 0.07s system 71% cpu 0.303 total
git --no-pager log --oneline -n10 HEAD                     0.04s user 0.01s system 76% cpu 0.070 total
git --no-pager log --oneline -n10 HEAD~10..HEAD            0.23s user 0.06s system 93% cpu 0.307 total
git --no-pager log --oneline -n20 HEAD~20..HEAD            0.23s user 0.07s system 96% cpu 0.307 total
git --no-pager log --oneline --graph HEAD~10..HEAD         0.19s user 0.07s system 92% cpu 0.273 total
git --no-pager log --oneline --graph HEAD~20..HEAD         0.18s user 0.07s system 96% cpu 0.261 total
git --no-pager log --oneline HEAD~10..HEAD                 0.24s user 0.07s system 94% cpu 0.327 total
git --no-pager log --oneline HEAD~20..HEAD                 0.23s user 0.08s system 96% cpu 0.323 total
git --no-pager log --oneline -n10 --graph                  0.06s user 0.04s system 90% cpu 0.108 total
git --no-pager log --oneline -n20 --graph                  0.14s user 0.07s system 95% cpu 0.220 total
git --no-pager log --oneline -n10                          0.04s user 0.01s system 77% cpu 0.069 total
git --no-pager log --oneline -n20                          0.04s user 0.02s system 82% cpu 0.071 total
```

**Comment by tarsius** [comment]
Please include the results for 100 and 1000 commits. You can skip the `HEAD` variants because those are the same as the respective variants without any rev or range.

**Comment by vermiculus** [comment]
Still including the HEAD variants because, well, I've seen weirder things happen with this migration project. Things that are conceptually identical can go down different codepaths. Providing HEAD for example requires Git to effectively rev-parse it rather than having the hard-coded HEAD already understood. The fact that this isn't demonstrated in the data (in fact, the opposite effect seems true) seems a fitting testament to how weird it can get.

```
( time_it 100 ${=args}; )    4.31s user  1.45s system 79% cpu    7.208 total   -n100 HEAD
( time_it 100 ${=args}; )    4.34s user  2.09s system 88% cpu    7.275 total   -n100
( time_it 100 ${=args}; )   17.44s user  6.70s system 96% cpu   24.935 total   -n100 --graph HEAD~100..HEAD
( time_it 100 ${=args}; )   18.57s user  6.86s system 96% cpu   26.253 total   -n100 --graph
( time_it 100 ${=args}; )   18.62s user  6.81s system 96% cpu   26.348 total   -n100 --graph HEAD
( time_it 100 ${=args}; )   37.11s user  7.31s system 97% cpu   45.681 total   --graph HEAD~100..HEAD
( time_it 100 ${=args}; )   47.94s user  7.17s system 98% cpu   56.200 total   -n100 HEAD~100..HEAD
( time_it 100 ${=args}; )   49.80s user  7.94s system 87% cpu 1:06.31  total   HEAD~100..HEAD

( time_it 100 ${=args}; )    5.40s user  3.00s system 89% cpu    9.417 total   -n1000 HEAD
( time_it 100 ${=args}; )    5.45s user  2.96s system 87% cpu    9.621 total   -n1000
( time_it 100 ${=args}; )  160.00s user  9.21s system 98% cpu 2:51.38  total   -n1000 --graph
( time_it 100 ${=args}; )  164.80s user  9.39s system 98% cpu 2:56.66  total   -n1000 --graph HEAD
( time_it 100 ${=args}; )  165.93s user  9.47s system 98% cpu 2:57.38  total   -n1000 --graph HEAD~1000..HEAD
( time_it 100 ${=args}; )  165.97s user 10.20s system 98% cpu 2:58.11  total   --graph HEAD~1000..HEAD
( time_it 100 ${=args}; )  209.30s user  9.25s system 98% cpu 3:41.03  total   -n1000 HEAD~1000..HEAD
( time_it 100 ${=args}; )  215.95s user 10.38s system 98% cpu 3:49.65  total   HEAD~1000..HEAD
```

**Comment by vermiculus** [comment]
Any other metrics I can add here?

**Comment by tarsius** [comment]
Sorry for not following up. I'm rather busy getting Forge into a releasable state, so that I can finally release "everything".

**Comment by tarsius** [comment]
<details>
<summary>Updated Script</summary>

```shell


git config --unset core.commitGraph

# Reorderered variants and added padding to increase
# readability and make reasoning easier.

# Results are the same as for the variants without HEAD.
# So I am omitting these variants, but feel free to add
# them back to verify this. (I have done that myself.)
#    "               -n10          HEAD"\
#    "--graph        -n10          HEAD"\

# Using bash to increase portability, that's a bit less
# flexible, so you must
# - edit the script, to change the number of runs,
# - edit the script, to change the number of commits.
```

</details>

The benchmark:

```
core.commitGraph=false                       -n10                      0.557
core.commitGraph=false                            HEAD~10..HEAD        1.613
core.commitGraph=false                       -n10 HEAD~10..HEAD        1.569
core.commitGraph=false        --graph        -n10                     63.776
core.commitGraph=false        --graph             HEAD~10..HEAD        1.555
core.commitGraph=false        --graph        -n10 HEAD~10..HEAD        1.500

core.commitGraph=true                        -n10                      0.545
core.commitGraph=true                             HEAD~10..HEAD        0.688
core.commitGraph=true                        -n10 HEAD~10..HEAD        0.630
core.commitGraph=true         --graph        -n10                      0.542
core.commitGraph=true         --graph             HEAD~10..HEAD        0.598
core.commitGraph=true         --graph        -n10 HEAD~10..HEAD        0.491
```

Conclusions:

1. Yes, without `--graph` we should drop the range.
2. With `--graph` and no commit-graph file, we still absolutely have to use the range.
3. With `--graph` and a commit-graph file, it doesn't make a difference.
4. 2+3= with `--graph`, always keep the range.

I could not find any documentation on how to get Git to automatically update the commit-graph file. It seems to me that Git should do that -- and by default.

I have done (1), but for unrelated reasons (https://github.com/progfolio/elpaca/issues/343#issuecomment-2308962826) I cannot push anything to `main` right now.

**Pull request closed without merging**
