### PR TITLE
add magit-log-move-to-parent command

### LINKED ISSUE #2686: move to 1st/2nd parent in log buffer
It would be great if in the log buffer you could navigate to the 1st or 2nd parent directly, when on a merge commit for instance.

### PR DESCRIPTION
**Pull request by kyleam**
Closes #2686.

### CODE REVIEW

**Comment by tarsius** [comment]
You  should use `magit-section-goto` to move to the section so that the `magit-section-movement-hook` is run. And if you do that anyway, it might be easier to find the appropriate section by looking in `(magit-section-siblings section 'next)` instead of doing a regexp search.

**Comment by kyleam** [comment]
> it might be easier to find the appropriate section by looking in
> (magit-section-siblings section 'next)

Ooh, thanks.  Will update with that (my) tonight.

**Comment by tarsius** [comment]
When there isn't an n-th parent, then this should probably raise a user-error.

**Comment by kyleam** [comment]
> When there isn't an n-th parent, then this should probably raise a user-error.

The updated version now raises distinct user errors in two cases:
1) The commit has no n-th parent.
2) The commit has an n-th parent, but it isn't visible in the current log.

**Comment by tarsius** [comment]
Nice

**Pull request merged**
