### PR TITLE
handle custom cygwin mounts

### LINKED ISSUE #2317: magit use hard-coded mount prefix
if an user customised the mount prefix in his cygwin / MINGW install, he is unable to use last magit version.

In function magit-expand-git-file-name (lisp/magit-git.el) the moun prefix is hard coded with cygdrive.

here is an attempt to fix this (this work for me with /mnt prefix) :
Sorry I was unable to attach it with a file.
```text
[PATCH] * lisp/magit-git.el magit-cygwin-prefix
 magit-expand-git-file-name

Use `magit-cygwin-prefix' in `magit-expand-git-file-name' instead of
hard-coded cygdrive prefix.
---
 lisp/magit-git.el | 11 ++++++++++-
 1 file changed, 10 insertions(+), 1 deletion(-)

diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index 22327f6..add2739 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -509,11 +509,20 @@ range.  Otherwise, it can be any revision or range accepted by
         (setq pos (point)))
       status)))
 
+(defconst magit-cygwin-prefix
+  (with-temp-buffer
+    (call-process-shell-command "mount -p | tail -1 | cut -d ' ' -f1" nil t)
+    (forward-line -1)
+    (setq cygwin-prefix (buffer-substring-no-properties
+                         (+ 1 (point)) (line-end-position)))))
+
 (defun magit-expand-git-file-name (filename)
   (unless (file-name-absolute-p filename)
     (setq filename (expand-file-name filename)))
   (if (and (eq system-type 'windows-nt) ; together with cygwin git, see #1318
-           (string-match "^/\\(cygdrive/\\)?\\([a-z]\\)/\\(.*\\)" filename))
+           (string-match
+            (concat "^/\\(" magit-cygwin-prefix "/\\)?\\([a-z]\\)/\\(.*\\)")
+            filename))
       (concat (match-string 2 filename) ":/"
               (match-string 3 filename))
     filename))
-- 
2.5.2

```

### PR DESCRIPTION
**Pull request by npostavs**
```
Rely on the output from mount to tell us how to map cygwin paths into
native Windows paths.

This is also needed in git-commit; avoid a hard dependency on magit by
only loading magit-git in the case where we receive a bad path to
foo_EDITMSG (and falling back to the standard "/cygdrive" prefix if we
fail to load).
```
---
fix #2317
replace/ close #2324

### CODE REVIEW

**Comment by PierreTechoueyres** [comment]
Maybe you should have a look at `magit-clone` too. I've an spurious directory `d` created when cloning to my `~/projets` (which expand to `d:/home/ptechoueyres/projets`) directory.
I guess the directory path should be converted to an cygwin / msys path with a mount point.

**Comment by tarsius** [comment]
Thanks a lot!

**Comment by npostavs** [comment]
> Maybe you should have a look at magit-clone too. I've an spurious directory d created when cloning to my ~/projets (which expand to d:/home/ptechoueyres/projets) directory.
> I guess the directory path should be converted to an cygwin / msys path with a mount point.

I think cygwin programs should be able to take windows paths, so I don't understand why there should be a problem here.

**Comment by PierreTechoueyres** [comment]
> I think cygwin programs should be able to take windows paths, so I don't understand why there should be a problem here.

Yes. You're right.
After some investigations, the clone part work flawlessly. I must investigate more to find what goes wrong after the `git clone` part.
Thanks for your patience and for this patch.

**Pull request merged**
