### PR TITLE
Use the "noglob" option on Cygwin and MSYS2

### LINKED ISSUE #2246: Magit no longer works with cygwin ?
It seems magit version 20150907.504 doesn't work with cygwin on windows 

When I try to open magit-buffer with magit-status command :
magit-insert-head-header: Wrong type argument: stringp, nil

It was working fine with previous versions (with magit 2.1.0). Did you change something concerning how git command is running ?

Thanks

### PR DESCRIPTION
**Pull request by johnmastro**
By default, Cygwin and MSYS2 executables attempt to expand globs when
called by a program other than a Unix shell.  The intent is to provide
globbing when, for instance, using Cygwin's grep from the Windows
command prompt.

However, this causes problems when calling the Cygwin or MSYS2 git from
Magit in a native Windows Emacs.  The solution is to detect this
behavior and, when present, add "noglob" to the "CYGWIN" and "MSYS"
environment variables to disable it.

See https://cygwin.com/cygwin-ug-net/using-cygwinenv.html

Fixes #2246.

### CODE REVIEW

**Comment by tarsius** [comment]
Looks good to me. @npostavs?

**Comment by npostavs** [comment]
Yup, looks good to me too.

**Comment by johnmastro** [comment]
Thanks @tarsius and @npostavs!

**Comment by tarsius** [comment]
And thanks to you!

**Pull request merged**
