### PR TITLE
Remove 2 trailing double-quotes in documentation

### PR DESCRIPTION
**Pull request by DamienCassou**

### CODE REVIEW

**Comment by tarsius** [comment]
@DamienCassou you are not really removing two double-quotes but two incarnations of the same one ;-) Since I was touching the commit for demonstration purposes anyway, I have dropped the "2".

@kyleam @npostavs When regenerating the manual for an existing commit you now have to use `AMEND=t make texi`, which will update the version strings to `TAG-gPREVHASH+1`. If you used just `make texi` then `TAG-gHASH_FOR_REPLACED_COMMIT+1` would be used.

Of course for trivial changes like this you don't actually have to update the version strings at all.

I will likely make it possible to bump the version strings in just one of the manuals.

**Comment by kyleam** [comment]
I can't recall: Do we track magit.texi for compatibility with MELPA?
Or because you don't want to assume a machine building the source has
ox-texinfo+?  Some other reason?

**Comment by tarsius** [comment]
Primarily for Melpa, but `make` users not needing `ox-texinfo+` is another benefit.

**Comment by kyleam** [comment]
Yeah, not pretty, but what can you do

**Comment by tarsius** [comment]
Well in my function as a regular Melpa contributor my opinion is that there are much more important things to do than to support all the weird things upstreams do to generate their documentation :stuck_out_tongue_winking_eye:

**Pull request merged**
